### ISSUE TITLE
cli: autocomplete error handling

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#1038]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- 0.6.x

### Affected Resource(s)

- cli autocomplete

### Debug Output

```
➜  /tmp cdktf diffError: Usage Error: /private/tmp is not a cdktf project directory, no cdktf.json found or cdktf.json is missing language / app keys
    at Object.Usage (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/lib/errors.js:20:21)
    at Object.throwIfNotProjectDirectory (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/bin/cmds/helper/check-directory.js:38:31)
    at Object.handler (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/bin/cmds/diff.js:39:27)
    at /Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:9052
    at j (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:9021)
    at M.runCommand (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:7206)
    at Bt.[runYargsParserAndExecuteCommands] (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:54320)
    at Bt.parse (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:36968)
    at Bt.get [as argv] (/Users/sebastian/.nvm/versions/node/v14.17.6/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:57661)
(node:8575) UnhandledPromiseRejectionWarning: TypeError: explanatoryComment.replaceAll is not a function
```

### Expected Behavior

Doesn't throw an exception

### Actual Behavior

it blows up

### Steps to Reproduce

Use autocomplete for stack dependent commands like `diff`, `deploy` or `destroy` outside of a project or inside a project where no `cdktf.json` file is present.

### References

- #0000

**Comment by ansgarm** [comment]
Do you get the same error if you run a `diff` in that directory?
But you're right, we might want to not error there but rather show no completions or such.

**Comment by skorfmann** [comment]
> Do you get the same error if you run a `diff` in that directory?

Haven't checked, but I'm assuming this would be working then.

**Comment by ansgarm** [comment]
Just checked – that also errors:
```
cdktf diff                                                                                                                                                      11:44:06
Error: Usage Error: /Users/ansgar is not a cdktf project directory, no cdktf.json found or cdktf.json is missing language / app keys
    at Object.Usage (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/lib/errors.js:20:21)
    at Object.throwIfNotProjectDirectory (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/bin/cmds/helper/check-directory.js:38:31)
    at Object.handler (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/bin/cmds/diff.js:39:27)
    at /Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:9052
    at j (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:9021)
    at M.runCommand (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:7206)
    at Bt.[runYargsParserAndExecuteCommands] (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:54320)
    at Bt.parse (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:36968)
    at Bt.get [as argv] (/Users/ansgar/.config/yarn/global/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:57661)
```
which is a feature (at least to me). I think it improves a formerly cryptic error message when attempting commands in the wrong directory.

**Comment by skorfmann** [comment]
> which is a feature (at least to me). I think it improves a formerly cryptic error message when attempting commands in the wrong directory.

I'd get rid of the stack trace there.
