### ISSUE TITLE
MODULE_NOT_FOUND error on Windows setup

### ISSUE THREAD

**Issue by Giandom** [hashicorp/terraform-cdk#1044]
Hi,
I'm trying to install cdktf on Windows but I get the following error:

`
$ cdktf -h
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../../cdktf/lib/manifest'
Require stack:
- C:\Users\IEUser\AppData\Roaming\npm\node_modules\cdktf-cli\lib\util.js
- C:\Users\IEUser\AppData\Roaming\npm\node_modules\cdktf-cli\bin\cmds\helper\terraform.js
- C:\Users\IEUser\AppData\Roaming\npm\node_modules\cdktf-cli\bin\cdktf.js
- C:\Users\IEUser\AppData\Roaming\npm\node_modules\cdktf-cli\bin\cdktf
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\IEUser\AppData\Roaming\npm\node_modules\cdktf-cli\lib\util.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\cdktf-cli\\lib\\util.js',
    'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\cdktf-cli\\bin\\cmds\\helper\\terraform.js',
    'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\cdktf-cli\\bin\\cdktf.js',
    'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\cdktf-cli\\bin\\cdktf'
  ]
}
`

My node version is:
`
$ node --version
v14.17.6
`

My npm version is:
`
$ npm --version
7.24.0
`

I installed the cdktf-cli package with:
`
 npm install -g cdktf-cli
`

Any advice?

Thanks

**Comment by jsteinich** [comment]
Seems likely to be the same issue as #1033.

Also installing `cdktf` globally should be a workaround (`npm install -g cdktf`). Could also install the latest preview build (`npm install -g cdktf-cli@next`)

**Comment by Giandom** [comment]
Hi @jsteinich,
it works now, thanks!
