### ISSUE TITLE
Python cdktf get - Cannot find abortsignal

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-cdk#1201]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli: 0.7.0
Node: v14.17.0
Python: 3.8.5
Terraform: v1.0.9
OS: Windows 11

### Debug Output

Running `cdktf get` in my project with the following cdktf.json file:

```json
{
  "language": "python",
  "app": "python ./main.py",
  "terraformProviders": [
    "google@=3.88"
  ],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

I'm getting the following output:

```
 cdktf get
NOTE: Temp directory retained due to an error: C:\Users\danie\AppData\Local\Temp\temp-UsIzjn
Error: jsii compilation failed with non-zero exit code: 1
  | [2021-10-22T21:39:26.005] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.0.9" means you should take a "devDependency" on "constructs" at "10.0.9" (found "undefined")"
  | warning JSII6: A "peerDependency" on "cdktf" at "0.7.0" means you should take a "devDependency" on "cdktf" at "0.7.0" (found "undefined")"
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | node_modules/@types/node/child_process.d.ts:267:18 - error TS2304: Cannot find name 'AbortSignal'.
  |
  | 267         signal?: AbortSignal | undefined;
  |                      ~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: C:\Users\danie\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\jsii\bin\jsii --silence-warnings reserved-word
  | Workdir: C:\Users\danie\AppData\Local\Temp\temp-UsIzjn
  +----------------------------------------------------------------------------------
    at newError (C:\Users\danie\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\@skorfmann\jsii-srcmak\lib\util.js:58:20)
    at ChildProcess.<anonymous> (C:\Users\danie\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\@skorfmann\jsii-srcmak\lib\util.js:75:29)
    at Object.onceWrapper (events.js:483:26)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
⠦ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [2021-10-22T21:39:26.005] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.0.9" means you should take a "devDependency" on "constructs" at "10.0.9" (found "undefined")"
  | warning JSII6: A "peerDependency" on "cdktf" at "0.7.0" means you should take a "devDependency" on "cdktf" at "0.7.0" (found "undefined")"
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | node_modules/@types/node/child_process.d.ts:267:18 - error TS2304: Cannot find name 'AbortSignal'.
  |
  | 267         signal?: AbortSignal | undefined;
  |                      ~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: C:\Users\danie\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\jsii\bin\jsii --silence-warnings reserved-word
  | Workdir: C:\Users\danie\AppData\Local\Temp\temp-UsIzjn
  +----------------------------------------------------------------------------------
```

### References

- #0000

**Comment by DanielMSchmidt** [comment]
This should be solved now, right?

**Comment by DanielMSchmidt** [comment]
This should be solved by now, please let us know if it's still an issue and thanks a ton for reporting it 👍
