### ISSUE TITLE
Fail fast when `cdktf init` is run in a directory named `cdktf` (npm does not allow this)

### ISSUE THREAD

**Issue by capaj** [hashicorp/terraform-cdk#1284]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Debug Output

```
 ✘ capaj@capaj-ryzen-7-5900x  ~/work-repos/lob/picasso/cdktf   lambda-config-refactors  cdktf init
Welcome to CDK for Terraform!

By default, cdktf allows you to manage the state of your stacks using Terraform Cloud for free.
cdktf will request an API token for app.terraform.io using your browser.

If login is successful, cdktf will store the token in plain text in
the following file for use by subsequent Terraform commands:
    /home/capaj/.terraform.d/credentials.tfrc.json

Note: The local storage mode isn't recommended for storing the state of your stacks.

? Do you want to continue with Terraform Cloud remote state management? No
? What template do you want to use? typescript

Initializing a project using the typescript template.
? projectName: test
? projectDescription:test
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "cdktf" under a package
npm ERR! also called "cdktf". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/capaj/.npm/_logs/2021-11-10T13_26_11_765Z-debug.log
Error: Command failed: npm install  cdktf@^0.7.0 constructs@^10.0.0
    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at installDeps (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/templates/typescript/.hooks.sscaff.js:28:3)
    at Object.exports.post (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/templates/typescript/.hooks.sscaff.js:16:3)
    at executePostHook (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:81:37)
    at Object.sscaff (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:48:15)
    at async Object.runInit (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/bin/cmds/helper/init.js:108:5)
    at async Object.handler (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/bin/cmds/init.js:54:9)

Debug Information:
    Terraform CDK version: 0.7.0
    Terraform version: 1.0.10
(node:845426) UnhandledPromiseRejectionWarning: Error: Command failed: npm install  cdktf@^0.7.0 constructs@^10.0.0
    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at installDeps (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/templates/typescript/.hooks.sscaff.js:28:3)
    at Object.exports.post (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/templates/typescript/.hooks.sscaff.js:16:3)
    at executePostHook (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:81:37)
    at Object.sscaff (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:48:15)
    at async Object.runInit (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/bin/cmds/helper/init.js:108:5)
    at async Object.handler (/home/capaj/.nvm/versions/node/v14.17.4/lib/node_modules/cdktf-cli/bin/cmds/init.js:54:9)

```

### Expected Behavior

cdktf-cli should refuse to run for a folder named `cdktf` same as when the folder is not empty

### References

- #0000

**Comment by skorfmann** [comment]
>npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "cdktf" under a package
npm ERR! also called "cdktf". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

This a restriction by npm itself. There's nothing we can do about it.

**Comment by capaj** [comment]
@skorfmann I disagree. You could do a simple validation on the name of the folder and fail fast without even trying to invoke the costly `npm install` command which is just waste of users CPU time and network resources at that point.

**Comment by ansgarm** [comment]
Failing fast makes sense 👍
I'm going to reopen and adjust the title of this issue accordingly.

**Comment by jsteinich** [comment]
> Are there similar scenarios in the other languages as well? I'm wondering if this would be some sort of language specific list of reserved names.

I'm not aware of anything, but I can't say that I've tried to break builds with directory names.

**Comment by capaj** [comment]
@jsteinich this scenario happens most likely for a user who is new to cdktf and wants to test it out.
Not sure if this will be breaking builds anywhere as it is much less likely someone with be using this name for the parent folder.

**Comment by ansgarm** [comment]
If new npm versions don't have this requirement, I'd be okay with closing this as won't do 👍
