### ISSUE TITLE
awscc provider not working

### ISSUE THREAD

**Issue by mirsilstan** [hashicorp/terraform-cdk#1397]
Hi,

I have a small Java cdktf application and I am trying to add the awscc provider to the cdktf.json.
I tried several formats, with and without version:
  _"terraformProviders": [
    "awscc@~> 0.8"
  ],_

 and the cdktf get command is failing with the stack trace:
_Error: unknown type undefined
    at $8e.renderAttributeType (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:43:50957)
    at $8e.renderAttributesForBlock (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:43:51145)
    at $8e.resourceFrom (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:43:49571)
    at QX.parse (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:43:53591)
    at YX.emitProvider (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:44:4652)
    at new YX (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:44:4371)
    at aAe.generateTypeScript (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:50:6162)
    at async aAe.generate (/home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:50:6251)
    at async /home/mircea/.npm-global/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:370:6323
⠏ downloading and generating modules and providers...
unknown type undefined_

I know there is no prebuilt provider for awscc, but I was under the assumption that it's not required that a provider be prebuilt to use it in cdktf.

If there is of any importance, I am trying to use a recently added feature to a Lambda event source mapping, more details here:
https://github.com/hashicorp/terraform-provider-aws/issues/22068

Or is there something that I am doing wrong?

**Comment by skorfmann** [comment]
Thanks for creating this issue @mirsilstan - we'll have to check what the issue there is. Since the AWS CC provider is using a more recent protocol than most other providers, there might some cases which haven't been tested yet.

As workaround you could use the cloud control resource of the AWS Provider (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudcontrolapi_resource) - That's what the cdktf AWS CDK Adapter is using behind the scenes https://www.terraform.io/docs/cdktf/create-and-deploy/aws-adapter.html

**Comment by ansgarm** [comment]
This is most probably due to the `nested_type` used in the AWS CC Terraform provider.
There's an [open draft PR](https://github.com/hashicorp/terraform-cdk/pull/939) which is probably a bit stale by now. I started to work on that for the [AWS Adapter](https://cdk.tf/adapter) but I ended up using the `cloudcontrolapi_resource` which Sebastian also mentioned.

**Comment by tobiaskloss** [comment]
I am currently experiencing the same issue with another provider, `rewe-digital/sonarcloud`.
From a quick code-review they seem to be using nested types as well.
