### ISSUE TITLE
`cdktf get` for module failing with JSII5000

### ISSUE THREAD

**Issue by adrianord** [hashicorp/terraform-cdk#1475]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli version: 0.8.6
language: python
python version: 3.10.1

### Expected Behavior

`cdktf get` generates the code for the module into `imports`

### Actual Behavior

cdktf spits out the following error
```
NOTE: Temp directory retained due to an error: /tmp/temp-zW6ZGn
Error: jsii compilation failed with non-zero exit code: 1
  | [2022-01-10T17:59:22.933] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.0.29" means you should take a "devDependency" on "constructs" at "10.0.29" (found "undefined")"
  | warning JSII6: A "peerDependency" on "cdktf" at "0.8.6" means you should take a "devDependency" on "cdktf" at "0.8.6" (found "undefined")"
  | error JSII5000: Methods and properties cannot have names like "getXxx": those conflict with Java property getters. Rename "IamAccount.getCallerIdentity"
  | error JSII5000: Methods and properties cannot have names like "getXxx": those conflict with Java property getters. Rename "IamAccountOptions.getCallerIdentity"
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  +----------------------------------------------------------------------------------
  | Command: /home/aordonez/.nvm/versions/node/v16.13.1/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-zW6ZGn
  +----------------------------------------------------------------------------------
    at y (/home/aordonez/.nvm/versions/node/v16.13.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:40:1480)
    at ChildProcess.<anonymous> (/home/aordonez/.nvm/versions/node/v16.13.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:43:112)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
⠙ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [2022-01-10T17:59:22.933] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.0.29" means you should take a "devDependency" on "constructs" at "10.0.29" (found "undefined")"
  | warning JSII6: A "peerDependency" on "cdktf" at "0.8.6" means you should take a "devDependency" on "cdktf" at "0.8.6" (found "undefined")"
  | error JSII5000: Methods and properties cannot have names like "getXxx": those conflict with Java property getters. Rename "IamAccount.getCallerIdentity"
  | error JSII5000: Methods and properties cannot have names like "getXxx": those conflict with Java property getters. Rename "IamAccountOptions.getCallerIdentity"
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  +----------------------------------------------------------------------------------
  | Command: /home/aordonez/.nvm/versions/node/v16.13.1/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-zW6ZGn
  +----------------------------------------------------------------------------------
```

### Steps to Reproduce

1. Create new cdktf python project
2. Add `"terraform-aws-modules/iam/aws//modules/iam-account@ ~>4.8.0"` to cdktf.json under modules
3. run `cdktf get`

### Important Factoids

This is the cdktf.json I am use

```json
{
  "language": "python",
  "app": "<REDACTED>",
  "projectId": "<REDACTED>",
  "terraformProviders": [
  ],
  "terraformModules": [
    "terraform-aws-modules/iam/aws//modules/iam-account@ ~>4.8.0"
  ],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}


```

**Comment by jsteinich** [comment]
I think there is just something not working quite right with https://github.com/hashicorp/terraform-cdk/blob/84fb33a266e844a0088fb45953d4671e32fd5f7f/packages/%40cdktf/provider-generator/lib/get/generator/models/attribute-model.ts#L185
