### ISSUE TITLE
CI: Windows builds fail on `windows-latest` (aka `windows-2022`)

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1564]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Integration tests that run on windows don't work on `windows-latest` (which as of recently resolves to `windows-2022`). They do work on `windows-2019` to which we temporarily downgraded with this commit: https://github.com/hashicorp/terraform-cdk/commit/2e9e97509908a61859ab20b50a911d2850d0806e for now.

### Debug Output

```
D:\a\terraform-cdk\terraform-cdk\test\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | win32 | x64
gyp info find Python using Python version 3.9.10 found at "C:\hostedtoolcache\windows\Python\3.9.10\x64\python3.exe"
gyp http GET https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.13.2/node-v16.13.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.13.2/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v16.13.2/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v16.13.2/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v16.13.2/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.13.2/SHASUMS256.txt
gyp http 404 https://nodejs.org/download/release/v16.13.2/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.13.2/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v16.13.2/win-x64/node.lib
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! System Windows_NT 10.0.20348
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\terraform-cdk\terraform-cdk\test\node_modules\node-pty
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok
```
([source](https://github.com/hashicorp/terraform-cdk/runs/5182882855?check_suite_focus=true))

### Steps to Reproduce

Set `windows-2019` to `windows-latest` in `.github/workflows/update-snapshots.yml` and `.github/workflows/integration.yml`.

### Important Factoids

Builds fail with a `node-gyp` error. Apparently `lerna` depends on an old version of that package. Unfortunately `lerna` seems to be discontinued (not updated within a year). So we might need to find a replacement.

However, the error message seems to denote a `node-gyp` version of `8.3.0` which is less than the one specified in `lerna` (`5.something`). So maybe we can find a way to upgrade that version to `8.4` to resolve the [issue](https://github.com/nodejs/node-gyp/issues/2520).

### References

- https://github.com/nodejs/node-gyp/issues/2520

**Comment by ansgarm** [comment]
Our current workflows are running on `windows-2022`, so this issue is obsolete.
