### ISSUE TITLE
Fn.merge broken

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#1653]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf & Language Versions

cdktf - 0.9.4
node - 16.2.0
typescript

### Affected Resource(s)
Trying to merge two maps together, but the LSP complains that Fn.merge only accepts one argument. However, the terraform documentation for `merge` clearly states that it takes an unlimited amount of arguments (https://www.terraform.io/language/functions/merge)

```
  readonly ngtag: { [key: string]: string };
    const defaultTags = {
      "Name": "eks",
      "kubernetes.io/role/internal-elb": '1',
      "kubernetes.io/role/elb": '1',
      "kubernetes.io/cluster/cluster-name": 'shared',
      "k8s.io/cluster-autoscaler/enabled": 'true',
    };
this.tags = Fn.merge(defaultTags, customTags)
```

### Debug Output
`error| Expected 1 arguments, but got 2`
`error| Type 'string[]' is not assignable to type '{ [key: string]: string; }'. Index signature for type 'string' is missing in type 'string[]'.`

### Expected Behavior
I expect to be able to pass in multiple arguments into `Fn.merge()` and have it return a map. 

### Actual Behavior
I cannot use Fn.merge at all.

**Comment by ansgarm** [comment]
Hi @jin-ahn,
The CDKTF `Fn.merge` function expects a single array of all arguments to the function because variadic arguments are not supported by JSII (as far as I know).

So you'd need to change your code to:
```
this.tags = Fn.merge([defaultTags, customTags])
```

**Comment by jin-ahn** [comment]
@ansgarm thank you for the reply.

When I updated my code to that I get the following error `Type 'string[]' is not assignable to type '{ [key: string]: string; }'.    Index signature for type 'string' is missing in type 'string[]'.`

Im setting this.tags as `readonly ngtag: { [key: string]: string };`as thats whats required by the aws constructor

**Comment by ansgarm** [comment]
Ah!
It seems that `Fn.merge` wrongly returns `asList()` which in the end resolves to a ListToken which has the type `string[]` (which is something we probably could fix by making it return a Map token instead).
Long story short: Until we fix this, could you try the following:
```ts
this.tags = Fn.merge([defaultTags, customTags]) as any;
```
While I haven't tested it myself, I feel it might work 🙃

**Comment by jin-ahn** [comment]
@ansgarm 

after changing above and running `cdktf deploy` it returns the below error

```
Command output on stderr:                                                                                                                                                                                                                           │
    4    │                                                                                                                                                                                                                                                    │
    5    │    /Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:114                                                                                                                                       │
    6    │          throw new Error(                                                                                                                                                                                                                          │
    7    │                ^                         
Error: Found an encoded list token string in a scalar string context. Use 'Fn.element(list, 0)' (not 'list[0]') to extract elements from token lists.                                                                                           │
    9    │        at resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:114:13)                                                                                                                   │
   10    │        at Object.resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:61:16)                                                                                                             │
   11    │        at resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:207:39)                                                                                                                   │
   12    │        at Object.resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:61:16)                                                                                                             │
   13    │        at resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:207:39)                                                                                                                   │
   14    │        at Object.resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:61:16)                                                                                                             │
   15    │        at resolve (/Users//Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:207:39)                                                                                                                   │
   16    │        at Object.resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:61:16)                                                                                                             │
   17    │        at resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:207:39)                                                                                                                   │
   18    │        at Object.resolve (/Users/Development/cdktf/aws/eks-stack/node_modules/cdktf/lib/tokens/private/resolve.ts:61:16)                        
```

**Comment by jsteinich** [comment]
Wrapping with `Token.asStringMap` should work.

Changing to return a map token would probably be better than a list, but really that isn't fully correct either.

**Comment by jin-ahn** [comment]
Do I need to import something specific to use `asStringMap`

It says `asStringMap` doesn't exist. But I see `asString` but that doesn't work here.
```
import { TerraformOutput, ITerraformDependable, Token, Fn } from 'cdktf'

      this.ngtag = Token.asStringMap(Fn.merge([defaultTags, config.customtag]))
```

**Comment by jsteinich** [comment]
> Do I need to import something specific to use `asStringMap`

It was added in cdktf version 0.9.0, so it should be there. Make sure that your package version is on at least that.
