### ISSUE TITLE
Access network_interface generates an error

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform-cdk#1698]
### cdktf & Language Versions

cdktf version: **0.10.1**
language: **python**

### Affected Resource(s)

Access instance details

```
  #Query a GCP Image filtered by Family        
        gcp_image = DataGoogleComputeImage(self, id = "windows_image", family = "windows-2019", project="windows-cloud" )

        #Get the network interface
        net_int = ComputeInstanceNetworkInterface(subnetwork ="<SUBNETWORK>",subnetwork_project = "<SHARED-PROJECT>")

        #Create a new vm
        instance = ComputeInstance(self,id = "sample-vm", machine_type="e2-standard-4", name="cdktf-instance-1", 
                        boot_disk= ComputeInstanceBootDisk(initialize_params=ComputeInstanceBootDiskInitializeParams(image=gcp_image.name)),
                        network_interface=[net_int], zone= "us-east4-a"
        )

        #Output 
        TerraformOutput(self, "instance_ip", instance.network_interface[0].network_ip)
```

### Debug Output

```
    Traceback (most recent call last):
      File "/Users/user/terraform-learning/cdktf-gcp/gcp/main.py", line 37, in <module>
        GcpBasicVmStack(app, "gcp")
      File "/Users/user/.local/share/virtualenvs/gcp-XHqyQSdy/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/Users/user/terraform-learning/cdktf-gcp/gcp/main.py", line 34, in __init__
        TerraformOutput(self, "instance_ip", instance.network_interface[0].network_ip)
    TypeError: 'InterfaceDynamicProxy' object is not subscriptable
```

### Expected Behavior

Should be able to retrieve the instance ip in the output

### Actual Behavior

Exception

### References

- #0000

**Comment by jsteinich** [comment]
This isn't directly supported at this time. A possible workaround:
```python
TerraformOutput(self, "instance_ip", Fn.lookup(Fn.element(instance.network_interface, 0), "network_ip", "default"))
```

**Comment by lmayorga1980** [comment]
```terraform
TerraformOutput(self, "instance_ip", Fn.lookup(Fn.element(instance.network_interface, 0), "network_ip","default"))
```


```
Synth command: pipenv run python main.py
Error:         non-zero exit code 1

Command output on stderr:

    Traceback (most recent call last):
      File "/Users/user/terraform-learning/cdktf-gcp/gcp/main.py", line 38, in <module>
        GcpBasicVmStack(app, "gcp")
      File "/Users/user/.local/share/virtualenvs/gcp-XHqyQSdy/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/Users/user/terraform-learning/cdktf-gcp/gcp/main.py", line 35, in __init__
        TerraformOutput(self, "instance_ip", Fn.lookup(Fn.element(instance.network_interface, 0), "network_ip",default_value=""))
      File "/Users/user/.local/share/virtualenvs/gcp-XHqyQSdy/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
    TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Comment by jsteinich** [comment]
```python
TerraformOutput(self, "instance_ip", value=Fn.lookup(Fn.element(instance.network_interface, 0), "network_ip", "default"))
```

Missed explicitly setting the `value` property on the output.

**Comment by lmayorga1980** [comment]
The workaround works.

**Comment by jsteinich** [comment]
> @jsteinich do we already have another issue that is tracking the work required for this to function without the need for a workaround?

#25 or #1610 should cover it.
