### ISSUE TITLE
Re-enable windows test for provider add command for csharp

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1816]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Somehow the provider add command integration test [did fail](https://github.com/hashicorp/terraform-cdk/runs/6572021428?check_suite_focus=true) on windows

<details>
  <summary>test output</summary>
Note: failing tests are currently retried once (that's why there's two times the output, however, it is still weird that they fail differently)

```
FAIL csharp/provider-add-command/test.ts (150.755 s)
  provider add command
    pre-built
      × installs pre-built provider using nuget (56093 ms)

  ● provider add command › pre-built › installs pre-built provider using nuget

    expect(received).toContain(expected) // indexOf

    Expected substring: "<PackageReference Include=\"HashiCorp.Cdktf.Providers.Random\" Version=\"0.2.55\" />"
    Received string:    "﻿<Project Sdk=\"Microsoft.NET.Sdk\">·
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
      </PropertyGroup>·
      <ItemGroup>
        <PackageReference Include=\"HashiCorp.Cdktf\" Version=\"0.10.4\" />
      </ItemGroup>·
      <ItemGroup>·
        <ProjectReference Include=\".gen\\Providers.Null\\Providers.Null.csproj\" />·
      </ItemGroup>·
    </Project>"

      37 |       const proj = driver.readLocalFile("MyTerraformStack.csproj");
      38 |
    > 39 |       expect(proj).toContain(
         |                    ^
      40 |         '<PackageReference Include="HashiCorp.Cdktf.Providers.Random" Version="0.2.55" />'
      41 |       );
      42 |     }, 300_000);

      at csharp/provider-add-command/test.ts:39:20
      at fulfilled (csharp/provider-add-command/test.ts:5:58)

  ● provider add command › pre-built › installs pre-built provider using nuget

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `provider add command pre-built installs pre-built provider using nuget 1`

    - Snapshot  -  8
    + Received  + 10

      "Checking whether pre-built provider exists for the following constraints:
        provider: random
        version : =3.1.3
        language: csharp
    -   cdktf   : 0.10.4
    -
    -
    - Found pre-built provider.
    -
    - Installing package HashiCorp.Cdktf.Providers.Random @ 0.2.55 using \"dotnet add package HashiCorp.Cdktf.Providers.Random --version 0.2.55\".
    -
    - Package installed.
    +   cdktf   : 
    +
    +
    + Pre-built provider does not exist for the given constraints.
    +
    + Adding local provider registry.terraform.io/hashicorp/random with version constraint =3.1.3 to cdktf.json
    +
    + Local providers have been updated. Running cdktf get to update...
    +
    + Generated csharp constructs in the output directory: .gen
      "

      18 |         "random@=3.1.3", // this is not the latest version, but theres v0.2.55 of the pre-built provider resulting in exactly this package
      19 |       ]);
    > 20 |       expect(res.stdout).toMatchInlineSnapshot(`
         |                          ^
      21 |         "Checking whether pre-built provider exists for the following constraints:
      22 |           provider: random
      23 |           version : =3.1.3

      at csharp/provider-add-command/test.ts:20:26
      at fulfilled (csharp/provider-add-command/test.ts:5:58)

 › 1 snapshot failed.
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm run npx -- -u` to update them.
```

</details>

### References

* https://github.com/hashicorp/terraform-cdk/pull/1761

**Comment by jsteinich** [comment]
This is also failing for me on Linux as cdktf `0.11.0` is not satisfying the package requirement of `^0.10.3`.
