### ISSUE TITLE
`cdktf get` should not error when no providers and modules are specified

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-cdk#1843]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, when I run `cdktf get` in a project with no modules and providers specified, I get this error:

```
$ npm run get

> [REDACTED]@1.0.0 get
> cdktf get

Usage Error: Please specify providers or modules in "cdktf.json" config file
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Usage Error: Please specify providers or modules in "cdktf.json" config file
    at Object.Usage (/[REDACTED]/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:437:630)
    at Object.xlt (/[REDACTED]/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:470:3793)
    at async Py.handleCommand (/[REDACTED]/node_modules/cdktf-cli/bundle/bin/cdktf.js:69:6049)
    at async Q.handler (/[REDACTED]/node_modules/cdktf-cli/bundle/bin/cdktf.js:69:4144)
(node:13529) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(Use `node --trace-warnings ...` to show where the warning was created)
```

In a CD/CI scenario in a monorepo, some projects may have providers and modules, while others may not. Having to write a `package.json` inspection before running `cdktf get` is a bit redundant. If no references are specific in `cdktf.json`, then the command should do nothing and finish with success and not show stack traces, etc.

**Comment by jsteinich** [comment]
There has been some debate on this among the team in https://github.com/hashicorp/terraform-cdk/pull/1456. Having this use case should be helpful in making a final call.

**Comment by nikolay** [comment]
@jsteinich The use case is CD/CI, reusable GitHub Actions, etc. Imagine `npm install` erroring out, because you don't have any dependencies in `package.json` and there are tons of similar examples. Installing/generating 0 is a valid case just like installing/generating N (where N > 0) is!

**Comment by DanielMSchmidt** [comment]
We came to the same conclusion as you and merged the PR (#1456) it's going to be released as part of `0.12.0`
