### ISSUE TITLE
Windows Javascript error when running `cdktf init --template="python"`

### ISSUE THREAD

**Issue by afmsavage** [hashicorp/terraform-cdk#194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

No error.
### Actual Behavior

Experienced this error when using the CLI to init my Python project.
### Steps to Reproduce

Run `cdftf init --template="python"`
### References

![image](https://user-images.githubusercontent.com/29739267/87712406-36539a00-c76e-11ea-9d2f-7b26f8af3eba.png)

* #0000

**Comment by skorfmann** [comment]
Likely the same issue as https://github.com/hashicorp/terraform-cdk/issues/198

**Comment by skorfmann** [comment]
Can you confirm the [0.0.12](https://github.com/hashicorp/terraform-cdk/releases/tag/v0.0.12) is fixing your issue?

**Comment by afmsavage** [comment]
Nope, still same issue.  I am wondering if this has something to do with the fact that my nodejs is installed via scoop and not in default locations?  Here is the output of the command.

Another thing to note is that this error is occuring on a completely different one than what I used to first report the issue.

During the bootstrap process, I answered 'no' to having the state stored in TFcloud and then kept the defaults for the name/description of the project.

```
=>  cdk-tf cdktf init --template="python"
Welcome to CDK for Terraform!

By default, cdktf allows you to manage the state of your stacks using Terraform Cloud for free.
cdktf will request an API token for app.terraform.io using your browser.

If login is successful, cdktf will store the token in plain text in
the following file for use by subsequent Terraform commands:
    C:\Users\afmsa/.terraform.d/credentials.tfrc.json

Note: The local storage mode isn't recommended for storing the state of your stacks.

Do you want to continue with Terraform Cloud remote state management (yes/no)? no

We will now setup the project. Please enter the details for your project.
If you want to exit, press ^C.

Project Name: (default: 'cdk-tf')
Project Description: (default: 'A simple getting started project for cdktf.')
Creating a virtualenv for this project…
Pipfile: C:\dev\sandbox\cdk-tf\Pipfile
Using C:/Users/afmsa/.pyenv/pyenv-win/versions/3.7.5-amd64/python.exe (3.7.5) to create virtualenv…
[   =] Creating virtual environment...created virtual environment in 1921ms CPython3Windows(dest=C:\Users\afmsa\.virtualenvs\cdk-tf-8B0o9F6O, clear=False, global=False) with seeder FromAppData pip=latest setuptools=latest wheel=latest app_data_dir=C:\Users\afmsa\AppData\Local\pypa\virtualenv\seed-v1 via=copy
[  ==]
Successfully created virtual environment!
Virtualenv location: C:\Users\afmsa\.virtualenvs\cdk-tf-8B0o9F6O
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (a65489)!
Installing dependencies from Pipfile.lock (a65489)…
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing cdktf~=0.0.12…
Adding cdktf to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock (9c9bdd) out of date, updating to (a65489)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Success!
Updated Pipfile.lock (9c9bdd)!
Installing dependencies from Pipfile.lock (9c9bdd)…
  ================================ 9/9 - 00:00:06
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
cdktf init [OPTIONS]

Create a new cdktf project from a template.

Options:
  --version              Show version number                                                                   [boolean]  --disable-logging      Dont write log files. Supported using the env CDKTF_DISABLE_LOGGING.  [boolean] [default: true]  --log-level            Which log level should be written. Only supported via setting the env CDKTF_LOG_LEVEL  [string]  --template             The template name to be used to create a new project.[string] [choices: "python", "typescript"]  --project-name         The name of the project.                                                               [string]  --project-description  The description of the project.                                                        [string]  --dist                 Install dependencies from a "dist" directory (for development)                         [string]  --local                Use local state storage for generated Terraform.                     [boolean] [default: false]  --cdktf-version        The cdktf version to use while creating a new project.             [string] [default: "0.0.12"]  -h, --help             Show help                                                                             [boolean]
Error: Command failed: C:\Users\afmsa\scoop\persist\nodejs\bin\node_modules\cdktf-cli\bin\cdktf get
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.exports.post (C:\Users\afmsa\scoop\persist\nodejs\bin\node_modules\cdktf-cli\templates\python\.hooks.sscaff.js:32:3)
    at executePostHook (C:\Users\afmsa\scoop\persist\nodejs\bin\node_modules\cdktf-cli\node_modules\sscaff\lib\sscaff.js:61:37)
    at Object.sscaff (C:\Users\afmsa\scoop\persist\nodejs\bin\node_modules\cdktf-cli\node_modules\sscaff\lib\sscaff.js:28:15)
    at async Object.handler (C:\Users\afmsa\scoop\persist\nodejs\bin\node_modules\cdktf-cli\bin\cmds\init.js:89:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1748,
  stdout: null,
  stderr: null
}
```

![image](https://user-images.githubusercontent.com/29739267/88444135-32b0ba80-cde1-11ea-8a60-6ce5b009ef3b.png)
![image](https://user-images.githubusercontent.com/29739267/88444172-6c81c100-cde1-11ea-9f78-4043604f21b3.png)

**Comment by skorfmann** [comment]
> Nope, still same issue. I am wondering if this has something to do with the fact that my nodejs is installed via scoop and not in default locations? Here is the output of the command.

Hm, which node version are you using?

**Comment by jsteinich** [comment]
I'm actually getting the exact same error using a build from master. I'll try to troubleshoot further.

**Comment by jsteinich** [comment]
This [SO issue](https://stackoverflow.com/questions/10396305/npm-package-bin-script-for-windows) explains what I believe is happening, although I believe everything is set correctly.

I was trying to run directly without an npm install to generate the wrapper, so my error was probably a bit different.

**Comment by jsteinich** [comment]
After working around #268 I am not at the same point and see the issue.

**Comment by skorfmann** [comment]
Thanks for looking into it @jsteinich
