### ISSUE TITLE
Cannot generate EKS Managed Nodegroup submodule using cdktf get

### ISSUE THREAD

**Issue by pchaganti** [hashicorp/terraform-cdk#1967]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.12 and python 3.7

### Affected Resource(s)

eks_eks-managed-node-group

### Debug Output
```
⠇ downloading and generating modules and providers...

NOTE: Temp directory retained due to an error: /tmp/temp-Zfzgc0
Error: Python moduleName [eks_eks-managed-node-group] may not contain "-"
    at ict (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:287)
    at lct (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:1720)
    at /home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:4266
    at async rct (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:52:1031)
    at async Object.yct (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:4193)
    at async /home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:58:4042
    at async M1e (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:46:1357)
    at async Eve (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:58:4006)
    at async WV.generate (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:61:192)
    at async DQ (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:438:1440)
```

### Expected Behavior

submodule is generated and available for use

### Actual Behavior

Error listed above

### Steps to Reproduce

Run cdktf get with the following cdktf.json
```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "projectId": "85a6-f1418c866e76-1ac8c531-1bdb-49f6",
  "sendCrashReports": "false",
  "terraformProviders": [
    {
      "name": "aws",
      "source": "hashicorp/aws",
      "version": "4.23.0"
    },
    {
      "name": "kubernetes",
      "source": "hashicorp/kubernetes",
      "version": "2.12.1"
    }
  ],
  "terraformModules": [
    {
      "name": "vpc",
      "source": "terraform-aws-modules/vpc/aws",
      "version": "3.14.2"
    },
    {
      "name": "eks",
      "source": "terraform-aws-modules/eks/aws",
      "version": "18.26.6"
    },
    {
      "name": "eks_eks-managed-node-group",
      "source": "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
    }
  ],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

### References
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group

**Comment by pchaganti** [comment]
Copy pasted the submodule definition from terraform site. Changing the name to remove hyphens works.

**Comment by jsteinich** [comment]
@pchaganti if you switch to the short form import (just have the string `terraform-aws-modules/eks/aws//modules/eks-managed-node-group`) then it should work. When you explicitly specify the name of the module (via `"name": "..."`) that name is taken literally (could also take out the `-` from the specified name).
