### ISSUE TITLE
 Unexpected token '?' error when running  cdktf --version

### ISSUE THREAD

**Issue by vbebins** [hashicorp/terraform-cdk#2003]
cdktf --version

The above command is throwing the following error?

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\bebins.velmurugan\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cdktf:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

npm install -g cdktf-cli@next - This is successful however the above command is not working.

What could be the reason?
Any help would be appreciated.

**Comment by DanielMSchmidt** [comment]
Which node version are you using? It could be that you are on one that does not support optional chaining. We support Node 14 and upwards

**Comment by vbebins** [comment]
Hi @DanielMSchmidt,

Yes, you are right.

My local node version is v12.18.2, after upgrading to the latest version it works.

Thanks for your support.
