### ISSUE TITLE
pre-built provider azurerm: trying to add provider for azurerm to go app returns error of invalid version

### ISSUE THREAD

**Issue by elduddz** [hashicorp/terraform-cdk#2065]
Running `cdktf provider add "azurerm"`

```
C:\g\tfcdk\aci> cdktf provider add "azurerm"
Checking whether pre-built provider exists for the following constraints:
  provider: azurerm
  version : latest
  language: go
  cdktf   : 0.12.1

Found pre-built provider.
Adding package github.com/hashicorp/cdktf-provider-azurerm-go/azurerm @ 2.0.10
[2022-08-19T11:26:27.556] [ERROR] default - go get: github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.10: invalid version: unknown revision azurerm/v2.0.10

go get: github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.10: invalid version: unknown revision azurerm/v2.0.10
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:433:933)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at e.emit (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:139:20414)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Collecting Debug Information...
C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: non-zero exit code 1
    at ChildProcess.<anonymous> (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:433:933)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at e.emit (C:\Users\auser\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:139:20414)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  stderr: 'go get: github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.10: invalid version: unknown revision azurerm/v2.0.10\n'
}

```

**Comment by ansgarm** [comment]
Hi @elduddz 👋

It seems that the Go package for the azurerm pre-built provider [failed to be released due to an out of memory error](https://github.com/hashicorp/cdktf-provider-azurerm/runs/7663450333?check_suite_focus=true) for version 2.0.10. And we use the available latest NPM package to find out which pre-built provider versions are available (as they usually are released in sync for all languages).

In the meantime you could try using either the `--force-local` flag which will result in locally generated bindings (note: this currently requires quite some memory to build for that provider) or you could install the latest pre-built package that is available for go ([repo](https://github.com/hashicorp/cdktf-provider-azurerm-go)) manually using:
```
go get github.com/hashicorp/cdktf-provider-azurerm-go/azurerm/v2@v2.0.2
```
