### ISSUE TITLE
Unqualified TerraformResourceLifecycle in Python bindings

### ISSUE THREAD

**Issue by jarpy** [hashicorp/terraform-cdk#2076]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
Terraform v1.2.8 on linux_amd64
CDTFK 0.12.2
Python 3.10.4
```

### Affected Resource(s)

All (I think), when declaring lifecycle options like `prevent_destroy`.

### Debug Output

https://gist.github.com/jarpy/ff1d4239bd47fb7b076796111633e572

### Expected Behavior

Synth should complete.

### Actual Behavior

Synth fails with:

```
    Traceback (most recent call last):
      File "/repro/main.py", line 21, in <module>
        File(scope=app, id_="f", filename="bob", lifecycle={"prevent_destroy": True})
      File "/root/.local/share/virtualenvs/repro-HuHhMKYP/lib/python3.10/site-packages/jsii/_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/repro/imports/local/__init__.py", line 625, in __init__
        config = FileConfig(
      File "/repro/imports/local/__init__.py", line 878, in __init__
        lifecycle = TerraformResourceLifecycle(**lifecycle)
    NameError: name 'TerraformResourceLifecycle' is not defined
```

### Steps to Reproduce

The following Dockerfile reproduces the issue:

```dockerfile
FROM ubuntu:22.04

## Basic dependencies.
RUN apt-get update
RUN apt-get install -y curl gnupg software-properties-common wget python3-pip vim
RUN pip install pipenv

## Install Terraform.
RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list
RUN apt-get update
RUN apt-get install -y terraform

## Install NodeJS and CDKTF.
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
RUN apt-get install -y nodejs
RUN npm install --location=global cdktf-cli@latest

## Create the reproduction.
RUN mkdir /repro
WORKDIR /repro
RUN cdktf init --template=python --local --project-name=repro --project-description=repro --enable-crash-reporting=false
# Use the "local" provider, becuase it is well understood.
RUN sed -i 's|"terraformProviders": \[\]|"terraformProviders": ["local@ ~> 2.2.3"]|' cdktf.json
RUN cdktf get

# Create a stack.
RUN echo 'from cdktf import App, TerraformStack' > main.py
RUN echo 'from imports.local import File' >> main.py
RUN echo 'app = App()' >> main.py
RUN echo 'TerraformStack(scope=app, id="stack")' >> main.py

# Declare a lifecycle rule to trigger the failure.
RUN echo 'File(scope=app, id_="f", filename="bob", lifecycle={"prevent_destroy": True})' >> main.py

## Run the repro.
RUN echo 'app.synth()' >> main.py
RUN cdktf synth
```

### Important Factoids

The generated provider contains lines like this:

```python
lifecycle = TerraformResourceLifecycle(**lifecycle)
```

...but the generated provider contains no import statement that would bring `TerraformResourceLifecycle` into the namespace.

```python
import abc
import builtins
import datetime
import enum
import typing
import jsii
import publication
import typing_extensions
from typeguard import check_type
from ._jsii import *
import cdktf
import constructs
```

Manually adding:
```python
from cdtkf import TerraformResourceLifecycle
```
...works around the issue.

**Comment by jarpy** [comment]
This appears to have been resolved. Today, the repro above fails with 

```
jsii.errors.JSIIError: No stack could be identified for the construct at path 'f'
```

That's a bug in the repro, and it's on me. I didn't see it before, becuase the primary issue masked it.

The original problem no longer manifests, and all the references to `TerraformResourceLifecyleProvider` in the provider are fully qualified.

```
root@b550009c31ad:/repro# more imports/local/__init__.py  | grep TerraformResourceLifecycle
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
            lifecycle = cdktf.TerraformResourceLifecycle(**lifecycle)
    def lifecycle(self) -> typing.Optional[cdktf.TerraformResourceLifecycle]:
        return typing.cast(typing.Optional[cdktf.TerraformResourceLifecycle], result)
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
            lifecycle = cdktf.TerraformResourceLifecycle(**lifecycle)
    def lifecycle(self) -> typing.Optional[cdktf.TerraformResourceLifecycle]:
        return typing.cast(typing.Optional[cdktf.TerraformResourceLifecycle], result)
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
            lifecycle = cdktf.TerraformResourceLifecycle(**lifecycle)
    def lifecycle(self) -> typing.Optional[cdktf.TerraformResourceLifecycle]:
        return typing.cast(typing.Optional[cdktf.TerraformResourceLifecycle], result)
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
        lifecycle: typing.Optional[typing.Union[cdktf.TerraformResourceLifecycle, typing.Dict[str, typing.Any]]] = None,
            lifecycle = cdktf.TerraformResourceLifecycle(**lifecycle)
    def lifecycle(self) -> typing.Optional[cdktf.TerraformResourceLifecycle]:
        return typing.cast(typing.Optional[cdktf.TerraformResourceLifecycle], result)
```

I'd love to know what changed, but it's just professional curiosity at this point. ❤️
