### ISSUE TITLE
Getting started - error generating constructs for TF providers

### ISSUE THREAD

**Issue by cmclaughlin** [hashicorp/terraform-cdk#208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Just read about this project on the AWS blog and giving it a try for the first time.
Here's what I ran to get an environment setup...

```
brew upgrade npm
npm install -g cdktf-cli
```

That gave me `cdktf-cli@0.0.12`

I setup a Python env like this:

```
pyenv shell 3.8.2
pyenv virtualenv cdktf
pyenv activate cdktf
pip install pipenv
```

And tried to setup a new project:

```
cdktf init --template=python --local
```

### Expected Behavior

New stack/template with no errors.

### Actual Behavior

```
$ cdktf init --template=python --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.tfstate' in the root of your project.

We will now setup the project. Please enter the details for your project.
If you want to exit, press ^C.

Project Name: (default: 'example7')
Project Description: (default: 'A simple getting started project for cdktf.')
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (a65489)!
Installing dependencies from Pipfile.lock (a65489)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing cdktf~=0.0.12…
Adding cdktf to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (a65489) out of date, updating to (9c9bdd)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (9c9bdd)!
Installing dependencies from Pipfile.lock (9c9bdd)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
⠋ downloading and generating providers...
⠙ downloading and generating providers...
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cdktf-cli/lib/util.js:89:27)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
non-zero exit code 1
cdktf init [OPTIONS]

Create a new cdktf project from a template.

Options:
  --version              Show version number                           [boolean]
  --disable-logging      Dont write log files. Supported using the env
                         CDKTF_DISABLE_LOGGING.        [boolean] [default: true]
  --log-level            Which log level should be written. Only supported via
                         setting the env CDKTF_LOG_LEVEL                [string]
  --template             The template name to be used to create a new project.
                                      [string] [choices: "python", "typescript"]
  --project-name         The name of the project.                       [string]
  --project-description  The description of the project.                [string]
  --dist                 Install dependencies from a "dist" directory (for
                         development)                                   [string]
  --local                Use local state storage for generated Terraform.
                                                      [boolean] [default: false]
  --cdktf-version        The cdktf version to use while creating a new project.
                                                    [string] [default: "0.0.12"]
  -h, --help             Show help                                     [boolean]

Error: Command failed: /usr/local/lib/node_modules/cdktf-cli/bin/cdktf get
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.exports.post (/usr/local/lib/node_modules/cdktf-cli/templates/python/.hooks.sscaff.js:32:3)
    at executePostHook (/usr/local/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/usr/local/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:28:15)
    at async Object.handler (/usr/local/lib/node_modules/cdktf-cli/bin/cmds/init.js:89:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 62643,
  stdout: null,
  stderr: null
}
```

`cdktf get` gives the same error:

```
$ cdktf get
⠹ downloading and generating providers...
Too many command line arguments. Configuration path expected.
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cdktf-cli/lib/util.js:89:27)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
non-zero exit code 1
```

### Steps to Reproduce

Run commands as listed above.

**Comment by blw9u2012** [comment]
@cmclaughlin I was also running into this issue but I wasn't running Terraform >= v0.12. Updating to Terraform `0.12.28` and rerunning the commands fixed my issue but I also confirmed that I had satisfied all of the prerequisites listed [here](https://github.com/hashicorp/terraform-cdk/blob/master/docs/getting-started/python.md):
```
Terraform >= v0.12
Node.js >= v12.16
Python >= v3.7
Pipenv
```

**Comment by skorfmann** [comment]
> @cmclaughlin I was also running into this issue but I wasn't running Terraform >= v0.12. Updating to Terraform `0.12.28` and rerunning the commands fixed my issue but I also confirmed that I had satisfied all of the prerequisites listed [here](https://github.com/hashicorp/terraform-cdk/blob/master/docs/getting-started/python.md):

Which version of Terraform were you running before the upgrade?

**Comment by cmclaughlin** [comment]
Whoops! I was using an old version of terraform by way of `tfenv`. Thanks for the help!
