### ISSUE TITLE
Generated typescript classes can override native js types

### ISSUE THREAD

**Issue by Codelax** [hashicorp/terraform-cdk#2137]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
language: go
cdktf-cli: 0.12.2
node: v16.17.0
cdktf: 0.12.0
constructs: 10.1.56
jsii: 1.62.0
terraform: 1.2.9
arch: x64
os: linux 5.19.8-200.fc36.x86_64
go: go version go1.19.1 linux/amd64

```

### Affected Resource(s)

`scaleway_object` with `scaleway/scaleway` terraform provider

### Debug Output

```
NOTE: Temp directory retained due to an error: /tmp/temp-r80tcN
Error: jsii compilation failed with non-zero exit code: 1
  | [2022-09-23T12:14:27.894] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.110" means you should take a "devDependency" on "constructs" at "10.1.110" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.12.2" means you should take a "devDependency" on "cdktf" at "0.12.2" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/scaleway/object.ts:171:35 - error TS2339: Property 'keys' does not exist on type 'typeof Object'.
  | 171       this.isEmptyObject = Object.keys(value).length === 0;
  |                                       ~~~~
  +----------------------------------------------------------------------------------
  | Command: /home/julescasteran/n/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-r80tcN
  +----------------------------------------------------------------------------------
    at p (/home/julescasteran/n/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:52:1581)
    at ChildProcess.<anonymous> (/home/julescasteran/n/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:112)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
⠴ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [2022-09-23T12:14:27.894] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.110" means you should take a "devDependency" on "constructs" at "10.1.110" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.12.2" means you should take a "devDependency" on "cdktf" at "0.12.2" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/scaleway/object.ts:171:35 - error TS2339: Property 'keys' does not exist on type 'typeof Object'.
  | 171       this.isEmptyObject = Object.keys(value).length === 0;
  |                                       ~~~~
  +----------------------------------------------------------------------------------
  | Command: /home/julescasteran/n/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-r80tcN
  +----------------------------------------------------------------------------------

```

### Expected Behavior

Provider `scaleway/scaleway` should generate and be usable

### Actual Behavior

When generating typescript code, `scaleway_object` resource get generated to `Object` and it shadow js `Object` type.

### Steps to Reproduce

`cdktf get scaleway/scaleway` (version v2.3.0)

### References

- #0000

**Comment by ansgarm** [comment]
Hi @Codelax 👋

Thank you for reporting this!

Interestingly enough I was just right now trying to figure out why our scaleway example failed for Go in an unrelated PR 😄

Seems like we need a special handling there 👍 (We already have such handlings in place for e.g. the `null` resource).
