### ISSUE TITLE
Issue @cdktf/provider-docker

### ISSUE THREAD

**Issue by samcrudge** [hashicorp/terraform-cdk#2209]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.14.0-pre.5
### Affected Provider / Resource(s)

@cdktf/provider-docker

### Debug Output
```bash
0 verbose cli /opt/homebrew/Cellar/node/18.11.0/bin/node /opt/homebrew/bin/npm
1 info using npm@8.19.2
2 info using node@v18.11.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/samuel.crudge/code/typescript-docker/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/samuel.crudge/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm list cdktf
23 verbose argv "list" "cdktf" "--json"
24 timing npm:load:setTitle Completed in 3ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/samuel.crudge/.npm/_logs
28 verbose logfile /Users/samuel.crudge/.npm/_logs/2022-10-20T13_04_00_092Z-debug-0.log
29 timing npm:load:logFile Completed in 3ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 21ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 2 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 1ms
37 timing command:list Completed in 117ms
38 verbose stack Error: invalid: cdktf@0.14.0-pre.5 /Users/samuel.crudge/code/typescript-docker/node_modules/cdktf
38 verbose stack     at LS.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/ls.js:205:9)
38 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli.js:78:5)
39 verbose cwd /Users/samuel.crudge/code/typescript-docker
40 verbose Darwin 21.6.0
41 verbose node v18.11.0
42 verbose npm  v8.19.2
43 error code ELSPROBLEMS
44 error invalid: cdktf@0.14.0-pre.5 /Users/samuel.crudge/code/typescript-docker/node_modules/cdktf
45 verbose exit 1
46 timing npm Completed in 178ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /Users/samuel.crudge/.npm/_logs/2022-10-20T13_04_00_092Z-debug-0.log
```

### Expected Behavior

Build without issue, I followed the guide on https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install#prerequisites.

the command `npm install @cdktf/provider-docker` had to be run with `--force`
### Actual Behavior

It built but this was the error at top of plan
```bash
[2022-10-20T14:04:00.269] [ERROR] default - npm ERR! code
npm ERR! code[2022-10-20T14:04:00.270] [ERROR] default -  ELSPROBLEMS
npm ERR! invalid: cdktf@0.14.0-pre.5 /Users/samuel.crudge/code/typescript-docker/node_modules/cdktf
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "invalid: cdktf@0.14.0-pre.5 /Users/samuel.crudge/code/typescript-docker/node_modules/cdktf",
    "detail": ""
  }
}

 ELSPROBLEMS
npm ERR! invalid: cdktf@0.14.0-pre.5 /Users/samuel.crudge/code/typescript-docker/node_modules/cdktf
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "invalid: cdktf@0.14.0-pre.5 /Users/samuel.crudge/code/typescript-docker/node_modules/cdktf",
    "detail": ""
  }
}
[2022-10-20T14:04:00.270] [ERROR] default - 
npm

npm[2022-10-20T14:04:00.270] [ERROR] default -  ERR! A complete log of this run can be found in:
npm ERR!
 ERR! A complete log of this run can be found in:
npm ERR![2022-10-20T14:04:00.270] [ERROR] default -      /Users/samuel.crudge/.npm/_logs/2022-10-20T13_04_00_092Z-debug-0.log
```
### Steps to Reproduce

```bash
npm install --global cdktf@next

npm install -g typescript  

npm install -g ts-node

npm install @cdktf/provider-docker   
<!--- This failed --->

npm install @cdktf/provider-docker  --force

cdktf get

cdktf deploy

```

### Important Factoids

I'm using an M1 Mac and I'm following https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install#prerequisites
### References

- #0000

**Comment by SamCrudge** [comment]
if i run without `--force` i get 
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: typescript-docker@1.0.0
npm ERR! Found: cdktf@0.14.0-pre.5
npm ERR! node_modules/cdktf
npm ERR!   cdktf@"^0.14.0-pre.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cdktf@"^0.13.0" from @cdktf/provider-docker@3.0.11
npm ERR! node_modules/@cdktf/provider-docker
npm ERR!   @cdktf/provider-docker@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/samuel.crudge/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samuel.crudge/.npm/_logs/2022-10-20T13_03_41_079Z-debug-0.log
```

**Comment by SamCrudge** [comment]
with i get 
```bash
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @cdktf/provider-docker@3.0.11
npm WARN Found: cdktf@0.14.0-pre.5
npm WARN node_modules/cdktf
npm WARN   cdktf@"^0.14.0-pre.5" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer cdktf@"^0.13.0" from @cdktf/provider-docker@3.0.11
npm WARN node_modules/@cdktf/provider-docker
npm WARN   @cdktf/provider-docker@"*" from the root project
npm WARN 
npm WARN Conflicting peer dependency: cdktf@0.13.1
npm WARN node_modules/cdktf
npm WARN   peer cdktf@"^0.13.0" from @cdktf/provider-docker@3.0.11
npm WARN   node_modules/@cdktf/provider-docker
npm WARN     @cdktf/provider-docker@"*" from the root project

added 1 package, and audited 353 packages in 752ms

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by SamCrudge** [comment]
Resolved the issue by removing NPM and reinstalling.
