### ISSUE TITLE
Support Node.js v19

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-cdk#2211]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for Node.js v19.0.0

### References

Node.js v19.0.0
cdktf v0.13.1

Currently, you get the following error during `synth`:

```
TypeError: Cannot set property crypto of #<Object> which has only a getter
    at <anonymous> (/Users/[REDACTED]/node_modules/@cdktf/hcl2json/wasm/bridge_wasm_exec.js:22:12)
    at Object.<anonymous> (/Users/[REDACTED]/node_modules/@cdktf/hcl2json/wasm/bridge_wasm_exec.js:28:22)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.v (/Users/[REDACTED]/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at <anonymous> (/Users/[REDACTED]/node_modules/@cdktf/hcl2json/lib/index.ts:35:5)
    at init (/Users/[REDACTED]/node_modules/@cdktf/hcl2json/lib/index.ts:35:5)
```

and also:

```
/Users/[REDACTED]/node_modules/@cdktf/hcl2json/wasm/bridge_wasm_exec.js:22
globalThis.crypto = {
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at Object.<anonymous> (/Users/[REDACTED]/node_modules/@cdktf/hcl2json/wasm/bridge_wasm_exec.js:22:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/[REDACTED]/node_modules/@cdktf/hcl2json/lib/index.js:49:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/Users/[REDACTED]/node_modules/@cdktf/hcl2json/lib/index.js:49:9)

```

**Comment by waffel** [comment]
Faced same issue after nodejs chocolate package is out for version 19.0.0

Got following stack trace:

```
C:\Users\XXX\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at Object.<anonymous> (C:\Users\z0017vtb\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\@cdktf\hcl2json\wasm\bridge_wasm_exec.js:22:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at C:\Users\z0017vtb\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\@cdktf\hcl2json\lib\index.js:49:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (C:\Users\XXX\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\@cdktf\hcl2json\lib\index.js:49:9)

Node.js v19.0.0
```

**Comment by matschaffer-roblox** [comment]
I bumped into this upgrading from 0.12.0 to 0.13. Seems like it's a new problem. Presumably with how hcl2json is attempting to load wasm in https://github.com/hashicorp/terraform-cdk/commit/0129a24482f341e995d2ad940af6fce40f646de9

That commit is in 0.12.3, so guessing anything after that won't support Node 19.

Downgrading node to 18.12.1 seems to get things working again.

**Comment by nikolay** [comment]
BTW, Homebrew installs Node.js v19 by default now, I saw that `cdktf` changed the dependency to `nodejs@18`, but that's wasteful!
