### ISSUE TITLE
cdktf deploy auto-approve error when ran on TFC workspace with cost estimation enabled

### ISSUE THREAD

**Issue by daniel-laszlo** [hashicorp/terraform-cdk#2232]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Python 3.9
CDKTF 0.13.2
Terraform Cloud

### Affected Resource(s)

`cdktf deploy STACK --auto-approve`

### Debug Output

```
Creating Terraform Cloud configuration version
Created Terraform Cloud configuration version cv-XXXXXXXXXXXXX
Zipping up the directory cdktf.out/stacks/STACK
Uploading the directory to Terraform Cloud
Uploaded the directory to Terraform Cloud
Waiting for configuration version to become ready...
Creating speculative Terraform Cloud run
Created speculative Terraform Cloud run: https://app.terraform.io/app/ORGANIZATION/workspaces/WORKSPACE_NAME/runs/run-XXXXXXXXXXXXXXXX
Speculative Terraform Cloud run done
Getting plan output
Deploying Terraform Cloud run


1 Stack deploying     0 Stacks done     0 Stacks waiting
[2022-10-31T14:34:34.126] [ERROR] default - Error in Deploy: {"message":"Request failed with status code 409","name":"Error","stack":"Error: Request failed with status code 409\n    at qqe.exports (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:151:8020)\n    at Lqe.exports (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:151:8198)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:152:8212)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"url":"/runs/run-XXXXXXXXXXXXXXXX/actions/apply","method":"post","data":"{}","headers":{"Authorization":"Bearer TOKEN","Accept":"application/json","Content-Type":"application/vnd.api+json","User-Agent":"terraform-cloud/1.15.0","Content-Length":2},"baseURL":"https://app.terraform.io/api/v2","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}
Deploy: Request to Terraform Cloud failed with status 409: {"status":"409","title":"transition not allowed"}

```

### Expected Behavior

First wait for cost estimation finish, then call TFC apply endpoint (`/runs/RUNID/actions/apply`).

### Actual Behavior

After plan finished, Terraform cloud `apply` endpoint was immediately called. Thus Terraform Cloud responded with `{"status":"409","title":"transition not allowed"}` which means [Run was not paused for confirmation; apply not allowed.](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#apply-a-run). I believe there were **two events ignored which resulted in this error: Cost estimation queued, Cost estimation finished.**

### Steps to Reproduce

1. Create Terraform Cloud workspace with manual apply and 'agent' workflow on an organization with cost estimation enabled.
2. Create stack with 3000+ resources
3. Set up a CloudBackend like this
```
CloudBackend(stack,
hostname="app.terraform.io",
organization=ORGANIZATION,
workspaces=NamedCloudWorkspace(name=workspace)
)
```
4. Run `cdktf deploy STACK --auto-approve`

### Important Factoids

The workspace has 3000+ resources.

**Comment by mutahhir** [comment]
These classes of issues were resolved in CDKTF 0.15 since we moved to using the Terraform CLI. If you're still encountering this issue with CDKTF versions 0.15 and greater, please reopen the issue. Thank you!
