### ISSUE TITLE
List type fields: Cannot find name ...List. Did you mean ...Map?

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-cdk#2333]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdftk-cli `0.14.1`
andrewbaxter/terraform-provider-stripe `v0.0.7`
node `v18.12.1`
npm `8.19.2`

### Affected Resource(s)

There are multiple, but `prices` is fundamental.

### Debug Output

https://github.com/andrewbaxter/terraform-provider-stripe

### Expected Behavior

Java should be generated fine, or else a descriptive error should be provided.

### Actual Behavior

Adding the provider fails with the error
```
$ ../node_modules/.bin/cdktf provider add andrewbaxter/stripe
Checking whether pre-built provider exists for the following constraints:
  provider: andrewbaxter/stripe
  version : latest
  language: java
  cdktf   : 0.14.1

Pre-built provider does not exist for the given constraints.
Adding local provider registry.terraform.io/andrewbaxter/stripe with version constraint undefined to cdktf.json
Local providers have been updated. Running cdktf get to update...
NOTE: Temp directory retained due to an error: /tmp/temp-jdvrkd
Error: jsii compilation failed with non-zero exit code: 1
  | [2022-11-23T02:24:22.678] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.167" means you should take a "devDependency" on "constructs" at "10.1.167" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.14.1" means you should take a "devDependency" on "cdktf" at "0.14.1" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/stripe/customers/index.ts:624:28 - error TS2552: Cannot find name 'CustomersTaxIdDataList'. Did you mean 'CustomersTaxIdDataMap'?
  | 624   private _taxIdData = new CustomersTaxIdDataList(this, "tax_id_data", false);
  |                                ~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/invoiceitems/index.ts:382:28 - error TS2552: Cannot find name 'InvoiceitemsDiscountsList'. Did you mean 'InvoiceitemsDiscountsMap'?
  | 382   private _discounts = new InvoiceitemsDiscountsList(this, "discounts", false);
  |                                ~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/invoices/index.ts:572:31 - error TS2552: Cannot find name 'InvoicesCustomFieldsList'. Did you mean 'InvoicesCustomFieldsMap'?
  | 572   private _customFields = new InvoicesCustomFieldsList(this, "custom_fields", false);
  |                                   ~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/invoices/index.ts:684:28 - error TS2552: Cannot find name 'InvoicesDiscountsList'. Did you mean 'InvoicesDiscountsMap'?
  | 684   private _discounts = new InvoicesDiscountsList(this, "discounts", false);
  |                                ~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/plans/index.ts:519:24 - error TS2304: Cannot find name 'PlansTiersList'.
  | 519   private _tiers = new PlansTiersList(this, "tiers", false);
  |                            ~~~~~~~~~~~~~~
  | providers/stripe/prices/index.ts:552:24 - error TS2304: Cannot find name 'PricesTiersList'.
  | 552   private _tiers = new PricesTiersList(this, "tiers", false);
  |                            ~~~~~~~~~~~~~~~
  | providers/stripe/subscriptions/index.ts:683:34 - error TS2552: Cannot find name 'SubscriptionsAddInvoiceItemsList'. Did you mean 'SubscriptionsAddInvoiceItemsMap'?
  | 683   private _addInvoiceItems = new SubscriptionsAddInvoiceItemsList(this, "add_invoice_items", false);
  |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/subscriptions/index.ts:968:24 - error TS2552: Cannot find name 'SubscriptionsItemsList'. Did you mean 'SubscriptionsItemsMap'?
  | 968   private _items = new SubscriptionsItemsList(this, "items", false);
  |                            ~~~~~~~~~~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /home/.../deploy/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-jdvrkd
  +----------------------------------------------------------------------------------
    at p (/home/.../deploy/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:52:1581)
    at ChildProcess.<anonymous> (/home/.../deploy/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:112)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
⠙ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [2022-11-23T02:24:22.678] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.167" means you should take a "devDependency" on "constructs" at "10.1.167" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.14.1" means you should take a "devDependency" on "cdktf" at "0.14.1" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/stripe/customers/index.ts:624:28 - error TS2552: Cannot find name 'CustomersTaxIdDataList'. Did you mean 'CustomersTaxIdDataMap'?
  | 624   private _taxIdData = new CustomersTaxIdDataList(this, "tax_id_data", false);
  |                                ~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/invoiceitems/index.ts:382:28 - error TS2552: Cannot find name 'InvoiceitemsDiscountsList'. Did you mean 'InvoiceitemsDiscountsMap'?
  | 382   private _discounts = new InvoiceitemsDiscountsList(this, "discounts", false);
  |                                ~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/invoices/index.ts:572:31 - error TS2552: Cannot find name 'InvoicesCustomFieldsList'. Did you mean 'InvoicesCustomFieldsMap'?
  | 572   private _customFields = new InvoicesCustomFieldsList(this, "custom_fields", false);
  |                                   ~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/invoices/index.ts:684:28 - error TS2552: Cannot find name 'InvoicesDiscountsList'. Did you mean 'InvoicesDiscountsMap'?
  | 684   private _discounts = new InvoicesDiscountsList(this, "discounts", false);
  |                                ~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/plans/index.ts:519:24 - error TS2304: Cannot find name 'PlansTiersList'.
  | 519   private _tiers = new PlansTiersList(this, "tiers", false);
  |                            ~~~~~~~~~~~~~~
  | providers/stripe/prices/index.ts:552:24 - error TS2304: Cannot find name 'PricesTiersList'.
  | 552   private _tiers = new PricesTiersList(this, "tiers", false);
  |                            ~~~~~~~~~~~~~~~
  | providers/stripe/subscriptions/index.ts:683:34 - error TS2552: Cannot find name 'SubscriptionsAddInvoiceItemsList'. Did you mean 'SubscriptionsAddInvoiceItemsMap'?
  | 683   private _addInvoiceItems = new SubscriptionsAddInvoiceItemsList(this, "add_invoice_items", false);
  |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/stripe/subscriptions/index.ts:968:24 - error TS2552: Cannot find name 'SubscriptionsItemsList'. Did you mean 'SubscriptionsItemsMap'?
  | 968   private _items = new SubscriptionsItemsList(this, "items", false);
  |                            ~~~~~~~~~~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /home/.../deploy/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-jdvrkd
  +----------------------------------------------------------------------------------
```

### Steps to Reproduce

Building the bindings should reproduce this.

### Important Factoids

The issue appears to be with `TypeList` fields.

The definition of `tiers` in price is
```
			"tiers": {
				Description: "Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.",
				Elem: &schema.Schema{
					Elem: &schema.Resource{Schema: map[string]*schema.Schema{
						"flat_amount": {
							Description: "",
							Optional:    true,
							Type:        schema.TypeInt,
						},
						"flat_amount_decimal": {
							Description: "",
							Optional:    true,
							Type:        schema.TypeString,
						},
						"unit_amount": {
							Description: "",
							Optional:    true,
							Type:        schema.TypeInt,
						},
						"unit_amount_decimal": {
							Description: "",
							Optional:    true,
							Type:        schema.TypeString,
						},
						"up_to": {
							Description: "",
							Required:    true,
							Type:        schema.TypeInt,
						},
					}},
					Type: schema.TypeMap,
				},
				ForceNew: true,
				Optional: true,
				Type:     schema.TypeList,
			},
```

It's very likely there's an issue with the provider itself, but without a better error message I have no way to identify the root cause.

### References

- #0000

**Comment by andrewbaxter** [comment]
All the resources have names that are plural, but I notice in `/tmp/temp-jdvrkd/providers/stripe` a singular version of some resources: prices, price, plans, plan, etc.  `PriceTierList` appears in `price` but the definition of `PricesTiersList` is missing in `prices`.

`price` is weird, it isn't referenced from `index.ts` at the provider root and _everything_'s been singularized -- all the hyperlinks in the documentation comments are wrong (linking to urls with price instead of prices, leading to a 404, etc): `https://www.terraform.io/docs/providers/stripe/r/price#billing_scheme`

It's like someone went through and did a `s/\bs//g` on all the files.

**Comment by andrewbaxter** [comment]
Okay, I identified one issue: I had two providers named stripe and typescript files were be generated for _both_ in the same directory, leading to files being overwritten etc.  This should really abort with an error if two providers have the same name, or better namespace things so that they're not writing to the same directory.

After digging around for a while, I finally removed the old provider from `cdktf.json` which stopped the generation of the extra files (which happened to have singular names).

I don't know why the urls were wrong still...

I haven't found any leads on the original issue with `List` and `Map` yet.

**Comment by ansgarm** [comment]
Hi 👋 I was able to confirm this locally.

It seems like the CDKTF has trouble properly handling this attribute type ("list of maps of object") 😅
```json
"tax_id_data": {
  "type": [
    "list",
    [
      "map",
      [
        "object",
        {
          "type": "string",
          "value": "string"
        }
      ]
    ]
  ],
  "description": "The customer's tax IDs.",
  "description_kind": "plain",
  "optional": true
},
```

Sidenote: Even though they don't seem that related, both this provider and the provider used in #2322 are based off of the same Terraform Plugin SDK version `v2.24.1`.

**Comment by andrewbaxter** [comment]
Ah thanks! Yeah sorry, that's the SDK version I'm using.

FWIW I probably didn't intend to nest things that way, but thanks for taking a look and having a fix will probably help me next time I mess this up!
