### ISSUE TITLE
CDKTF init fails when importing existing project

### ISSUE THREAD

**Issue by Khalarii** [hashicorp/terraform-cdk#2423]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF v0.14.3

### Affected Resource(s)

All

### Debug Output

```
Error: Error: HCL-JSON does not conform to schema. This is not expected, please file a bug under https://cdk.tf/bugs/new/convert
Please include this information:
[{"code":"invalid_union","unionErrors":[{"errors":[{"code":"invalid_type","expected":"object","received":"string","path":["variable","environment",0,"validation",0,"condition"],"message":"Expected object, received string"},{"code":"invalid_type","expected":"object","received":"string","path":["variable","environment",0,"validation",0,"error_message"],"message":"Expected object, received string"}]},{"errors":[{"code":"invalid_type","expected":"undefined","received":"array","path":["variable","environment",0,"validation"],"message":"Expected undefined, received array"}]}],"path":["variable","environment",0,"validation"],"message":"Invalid input"}]
    at getParsedHcl (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:62:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseProviderRequirements (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:71:18)
    at async $ot (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:1751)
    at async Object.zFr (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:26038)
    at async fp.handleCommand (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:31390)
    at async B.handler (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879)
Collecting Debug Information...
/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Error: HCL-JSON does not conform to schema. This is not expected, please file a bug under https://cdk.tf/bugs/new/convert
Please include this information:
[{"code":"invalid_union","unionErrors":[{"errors":[{"code":"invalid_type","expected":"object","received":"string","path":["variable","environment",0,"validation",0,"condition"],"message":"Expected object, received string"},{"code":"invalid_type","expected":"object","received":"string","path":["variable","environment",0,"validation",0,"error_message"],"message":"Expected object, received string"}]},{"errors":[{"code":"invalid_type","expected":"undefined","received":"array","path":["variable","environment",0,"validation"],"message":"Expected undefined, received array"}]}],"path":["variable","environment",0,"validation"],"message":"Invalid input"}]
    at getParsedHcl (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:62:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseProviderRequirements (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:71:18)
    at async $ot (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:1751)
    at async Object.zFr (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:26038)
    at async fp.handleCommand (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:31390)
    at async B.handler (/Users/username/.nvm/versions/node/v18.12.0/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879)

Node.js v18.12.0
```

### Expected Behavior

Create CDK project based on existing project.

### Actual Behavior

Application crashed.

### Steps to Reproduce

Run cdktf init command and pass in existing project path.

### Important Factoids

Real-world application infrastructure.

### References

None.

**Comment by ansgarm** [comment]
Hi @Khalarii 👋

From the error message it seems like `cdktf convert` currently does not support `validation` blocks in variable configurations.

You could try removing those, if you don't have lots of them to circumvent this until we support this kind of block (in convert, CDKTF itself supports `validation` blocks: [PR](https://github.com/hashicorp/terraform-cdk/pull/1533)).
