### ISSUE TITLE
ReferenceError mwait on cdktf java template initialization

### ISSUE THREAD

**Issue by zgeorge2** [hashicorp/terraform-cdk#2457]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

$ cdktf --version
0.14.3

### Expected Behavior
Ran the following command to init a terraform project for cdktf for java
$ cdktf init --template=java --local

cdktf should have completed initializing the directory without ANY ReferenceErrors

### Actual Behavior
The following errors are produced at the end of the cdktf run. 
...
ReferenceError: mawait is not defined
    at xDr (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:3218)
    at $ot (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:2828)
    at async Object.zFr (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:26039)
    at async fp.handleCommand (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:31390)
    at async B.handler (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879)
Collecting Debug Information...
/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

ReferenceError: mawait is not defined
    at xDr (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:3218)
    at $ot (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:2828)
    at async Object.zFr (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:26039)
    at async fp.handleCommand (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:31390)
    at async B.handler (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879)

Node.js v18.12.1

### Steps to Reproduce

$  cdktf init --template="java" --local
<enter an arbitrary name for the project and desription> e.g., "foo". 

### References

- #0000

**Comment by mutahhir** [comment]
Thanks for your report! I followed the steps to reproduce, but the project initializes without errors. I'm on the same version of Node and cdktf as you. Is there any additional context that can help me reproduce the issue?
