### ISSUE TITLE
AWS CC bindings can't be compiled

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2463]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

Should compile

### Actual Behavior

```
OTE: Temp directory retained due to an error: /var/folders/y5/nm6gc8rj0p76ds9pwyfz2xym0000gn/T/temp-numPox
Error: jsii compilation failed with non-zero exit code: 1
  | [2023-01-06T13:38:34.682] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.183" means you should take a "devDependency" on "constructs" at "10.1.183" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.14.3" means you should take a "devDependency" on "cdktf" at "0.14.3" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/awscc/backup-backup-plan/index.ts:94:5 - error TS2740: Type '{ [key: string]: string; }' is missing the following properties from type 'StringMap': terraformResource, terraformAttribute, lookup, computeFqn, and 3 more.
  | 94     return this.getStringMapAttribute('backup_options');
  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/databrew-job/index.ts:2089:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 2089     return this.getStringMapAttribute('parameters');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/databrew-job/index.ts:2420:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 2420     return this.getStringMapAttribute('parameters');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/iot-topic-rule/index.ts:2853:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 2853     return this.getStringMapAttribute('client_properties');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/iot-topic-rule/index.ts:7680:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 7680     return this.getStringMapAttribute('client_properties');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/y5/nm6gc8rj0p76ds9pwyfz2xym0000gn/T/temp-numPox
  +----------------------------------------------------------------------------------
    at p (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:51:1581)
    at ChildProcess.<anonymous> (/usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:54:112)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
⠋ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [2023-01-06T13:38:34.682] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.183" means you should take a "devDependency" on "constructs" at "10.1.183" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.14.3" means you should take a "devDependency" on "cdktf" at "0.14.3" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/awscc/backup-backup-plan/index.ts:94:5 - error TS2740: Type '{ [key: string]: string; }' is missing the following properties from type 'StringMap': terraformResource, terraformAttribute, lookup, computeFqn, and 3 more.
  | 94     return this.getStringMapAttribute('backup_options');
  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/databrew-job/index.ts:2089:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 2089     return this.getStringMapAttribute('parameters');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/databrew-job/index.ts:2420:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 2420     return this.getStringMapAttribute('parameters');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/iot-topic-rule/index.ts:2853:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 2853     return this.getStringMapAttribute('client_properties');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/awscc/iot-topic-rule/index.ts:7680:5 - error TS2322: Type '{ [key: string]: string; }' is not assignable to type 'StringMap'.
  | 7680     return this.getStringMapAttribute('client_properties');
  |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /usr/local/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/y5/nm6gc8rj0p76ds9pwyfz2xym0000gn/T/temp-numPox
  +----------------------------------
``` 

### Steps to Reproduce

Use this `cdktf.json` file:

```json
{
  "language": "python",
  "app": "pipenv run python main.py",
  "projectId": "2d650884-83c6-444f-9726-094c4a98476f",
  "sendCrashReports": "false",
  "terraformProviders": [
    {
      "name": "awscc",
      "source": "hashicorp/awscc",
      "version": "0.33.0"
    }
  ],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

Run `cdktf get`

### References

- [Discuss](https://discuss.hashicorp.com/t/bug-in-awscc-upgrade-from-0-32-0-to-0-33-0-and-onwards/48648)

**Comment by ansgarm** [comment]
There's also an issue about this reported in the awscc provider repo: https://github.com/hashicorp/terraform-provider-awscc/issues/808

**Comment by jsteinich** [comment]
I'm curious if #2372 would fix this. I'll see if I can add a test case.
