### ISSUE TITLE
CA Certificate Failed during cdktf init

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform-cdk#2500]
### cdktf & Language Versions

cdktf - 0.14.3

### Affected Resource(s)
```
cdktf init --template=python --local --project-name dockersample --project-description "Sample Docker CDKTF" 
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.<STACK NAME>.tfstate' in the root of your project.
? Do you want to send crash reports to the CDKTF team? See 
https://www.terraform.io/cdktf/create-and-deploy/configuration-file#enable-crash-reporting-for-the-cli for more information No
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (4e61a4ba9e6f02f50f68627253af5ababd9b1b4c1e10294e48158e1f42c0c5a6)!
Installing dependencies from Pipfile.lock (c0c5a6)...
Installing cdktf~=0.14.3...
Pipfile.lock (c0c5a6) out of date, updating to (ef3ea9)...
Locking [packages] dependencies...
⠇ Resolving dependencies...
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pipenv.patched.pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cdktf/json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 845, in <module>
    main()
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 831, in main
    _main(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 811, in _main
    resolve_packages(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 759, in resolve_packages
    results, resolver = resolve(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 738, in resolve
    return resolve_deps(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1100, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 900, in actually_resolve_deps
    hashes = resolver.resolve_hashes()
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 801, in resolve_hashes
    self.hashes[ireq] = self.collect_hashes(ireq)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 781, in collect_hashes
    hashes = self._get_hashes_from_pypi(ireq)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 741, in _get_hashes_from_pypi
    r = session.get(pkg_url, timeout=10)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
pipenv.patched.pip._vendor.requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cdktf/json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

Error: Command failed: pipenv install cdktf~=0.14.3
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at exports.post (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/templates/python/.hooks.sscaff.js:33:3)
    at s (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:195:6150)
    at Vvr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:195:5614)
    at async Kvr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:196:4)
    at async $ot (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:2125)
    at async Object.zFr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:26038)
    at async fp.handleCommand (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:31390)
Collecting Debug Information...
/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Command failed: pipenv install cdktf~=0.14.3
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at exports.post (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/templates/python/.hooks.sscaff.js:33:3)
    at s (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:195:6150)
    at Vvr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:195:5614)
    at async Kvr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:196:4)
    at async $ot (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:2125)
    at async Object.zFr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:26038)
    at async fp.handleCommand (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:31390) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 50284,
  stdout: null,
  stderr: null
}

Node.js v18.13.0
```

### Actual Behavior

I tried using `REQUEST_CA_BUNDLE` and `pip.conf` `cert` attribute for a custom ca bundle but it does not work.

### References

- #0000

**Comment by DanielMSchmidt** [comment]
I'm closing this in favor of #2499
