### ISSUE TITLE
C#: Operators can not be used in C#

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2557]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

`cdktf.Op.*`

### Expected Behavior

This should synthesise:

```csharp
DataAwsAvailabilityZones zones = new DataAwsAvailabilityZones(this, "zones", new DataAwsAvailabilityZonesConfig {
    State = "available"
});

new TerraformOutput(this, "half-of-the-zone", new TerraformOutputConfig {
    Value = Op.Div(Fn.LengthOf(zones.Names), 2)
});
```

(I also tried all variants with Token.AsNumber and Token.asAny)

### Actual Behavior

It fails:

```
[2023-01-31T11:23:23.835] [ERROR] default - System.ArgumentException: Could not infer JSII type for .NET type '_Proxy' (Parameter 'type')
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Type type)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.ConvertAny(Type type, IReferenceMap referenceMap, Object value)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertPrimitive(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, PrimitiveType primitiveType, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertClass(Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCustomType(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, String fullyQualifiedName, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.ConvertArguments(Parameter[] parameters, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at HashiCorp.Cdktf.TerraformOutput..ctor(Construct scope, String id, ITerraformOutputConfig config)
   at Examples.OperatorsStack..ctor(Construct scope, String name) in /Users/danielschmidt/work/terraform-cdk-3/examples/csharp/documentation/OperatorStack.cs:line 26
   at MyCompany.MyApp.MyApp.Main(String[] args) in /Users/danielschmidt/work/terraform-cdk-3/examples/csharp/
ERROR: cdktf encountered an error while synthesizing

Synth command: dotnet run -p MyTerraformStack.csproj
Error:         non-zero exit code 134
```

### References

- #0000

**Comment by DanielMSchmidt** [comment]
Yeah, that gives me the same error
