### ISSUE TITLE
Typescript errors from cdktf get

### ISSUE THREAD

**Issue by kh34** [hashicorp/terraform-cdk#2610]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```

cdktf debug
language: python
cdktf-cli: 0.15.3
node: v16.19.0
cdktf: 0.15.3
constructs: 10.1.185
jsii: 1.74.0
terraform: 1.3.7
arch: arm64
os: darwin 22.2.0
python: Python 3.10.9
pip: pip 22.3.1 from .../.venv/lib/python3.10/site-packages/pip (python 3.10)
pipenv: pipenv, version 2023.2.4

```

### Expected Behavior

Should compile

### Actual Behavior

```
$ cdktf get
[2023-02-07T16:55:55.804] [INFO] default - Could not find constraints.json file while filtering: Error: ENOENT: no such file or directory, open '.../imports/constraints.json'. This means no providers were generated, so all constraints need to be generated.
NOTE: Temp directory retained due to an error: /tmp/temp-pMRwX1
Error: jsii compilation failed with non-zero exit code: 1
  | [2023-02-07T16:56:04.421] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.185" means you should take a "devDependency" on "constructs" at "10.1.185" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.15.3" means you should take a "devDependency" on "cdktf" at "0.15.3" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | node_modules/@types/node/ts4.8/util.d.ts:1485:42 - error TS1005: ',' expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:44 - error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                 ~~~~~~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:57 - error TS1005: ';' expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                              ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:65 - error TS1005: ';' expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:66 - error TS1109: Expression expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                                       ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:67 - error TS1109: Expression expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                                        ~
  | node_modules/@types/node/ts4.8/util.d.ts:1490:17 - error TS1005: ',' expected.
  | 1490         get(name: string): string | null;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1490:26 - error TS1005: ';' expected.
  | 1490         get(name: string): string | null;
  |                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1494:17 - error TS1005: ',' expected.
  | 1494         has(name: string): boolean;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1494:26 - error TS1005: ';' expected.
  | 1494         has(name: string): boolean;
  |                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1498:15 - error TS1005: ';' expected.
  | 1498         keys(): IterableIterator<string>;
  |                    ~
  | node_modules/@types/node/ts4.8/util.d.ts:1498:41 - error TS1005: '(' expected.
  | 1498         keys(): IterableIterator<string>;
  |                                              ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:17 - error TS1005: ',' expected.
  | 1504         set(name: string, value: string): void;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:32 - error TS1005: ',' expected.
  | 1504         set(name: string, value: string): void;
  |                                     ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:41 - error TS1005: ';' expected.
  | 1504         set(name: string, value: string): void;
  |                                              ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:47 - error TS1109: Expression expected.
  | 1504         set(name: string, value: string): void;
  |                                                    ~
  | node_modules/@types/node/ts4.8/util.d.ts:1508:17 - error TS1005: ';' expected.
  | 1508         values(): IterableIterator<string>;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1508:43 - error TS1005: '(' expected.
  | 1508         values(): IterableIterator<string>;
  |                                                ~
  | node_modules/@types/node/ts4.8/util.d.ts:1512:26 - error TS1005: ';' expected.
  | 1512         [Symbol.iterator]: typeof MIMEParams.prototype.entries;
  |                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1514:1 - error TS1128: Declaration or statement expected.
  | 1514 }
  |      ~
  +----------------------------------------------------------------------------------
  | Command: /usr/local/lib/.npm-packages/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-pMRwX1
  +----------------------------------------------------------------------------------
    at p (/usr/local/lib/.npm-packages/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:52:1581)
    at ChildProcess.<anonymous> (/usr/local/lib/.npm-packages/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:55:112)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
⠹ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [2023-02-07T16:56:04.421] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII6: A "peerDependency" on "constructs" at "10.1.185" means you should take a "devDependency" on "constructs" at "10.1.185" (found "undefined")
  | warning JSII6: A "peerDependency" on "cdktf" at "0.15.3" means you should take a "devDependency" on "cdktf" at "0.15.3" (found "undefined")
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | node_modules/@types/node/ts4.8/util.d.ts:1485:42 - error TS1005: ',' expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:44 - error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                 ~~~~~~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:57 - error TS1005: ';' expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                              ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:65 - error TS1005: ';' expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:66 - error TS1109: Expression expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                                       ~
  | node_modules/@types/node/ts4.8/util.d.ts:1485:67 - error TS1109: Expression expected.
  | 1485         entries(): IterableIterator<[name: string, value: string]>;
  |                                                                        ~
  | node_modules/@types/node/ts4.8/util.d.ts:1490:17 - error TS1005: ',' expected.
  | 1490         get(name: string): string | null;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1490:26 - error TS1005: ';' expected.
  | 1490         get(name: string): string | null;
  |                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1494:17 - error TS1005: ',' expected.
  | 1494         has(name: string): boolean;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1494:26 - error TS1005: ';' expected.
  | 1494         has(name: string): boolean;
  |                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1498:15 - error TS1005: ';' expected.
  | 1498         keys(): IterableIterator<string>;
  |                    ~
  | node_modules/@types/node/ts4.8/util.d.ts:1498:41 - error TS1005: '(' expected.
  | 1498         keys(): IterableIterator<string>;
  |                                              ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:17 - error TS1005: ',' expected.
  | 1504         set(name: string, value: string): void;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:32 - error TS1005: ',' expected.
  | 1504         set(name: string, value: string): void;
  |                                     ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:41 - error TS1005: ';' expected.
  | 1504         set(name: string, value: string): void;
  |                                              ~
  | node_modules/@types/node/ts4.8/util.d.ts:1504:47 - error TS1109: Expression expected.
  | 1504         set(name: string, value: string): void;
  |                                                    ~
  | node_modules/@types/node/ts4.8/util.d.ts:1508:17 - error TS1005: ';' expected.
  | 1508         values(): IterableIterator<string>;
  |                      ~
  | node_modules/@types/node/ts4.8/util.d.ts:1508:43 - error TS1005: '(' expected.
  | 1508         values(): IterableIterator<string>;
  |                                                ~
  | node_modules/@types/node/ts4.8/util.d.ts:1512:26 - error TS1005: ';' expected.
  | 1512         [Symbol.iterator]: typeof MIMEParams.prototype.entries;
  |                               ~
  | node_modules/@types/node/ts4.8/util.d.ts:1514:1 - error TS1128: Declaration or statement expected.
  | 1514 }
  |      ~
  +----------------------------------------------------------------------------------
  | Command: /usr/local/lib/.npm-packages/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-pMRwX1
  +----------------------------------------------------------------------------------
```

### Steps to Reproduce

Use this cdktf.json file:

```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "projectId": "2d650884-83c6-444f-9726-094c4a98476f",
  "sendCrashReports": "false",
  "terraformProviders": [
    {
      "name": "awscc",
      "source": "hashicorp/awscc",
      "version": "0.33.0"
    }
  ],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}


```

### Important Factoids

Workaround:

To see compatible types for `typescript 3.9.10`:

```
npm dist-tags @types/node 

npm uninstall --global cdktf-cli
npm install --global cdktf-cli@0.15.3 @types/node@17.0.41 #NOTE must be installed at same time
```

It seems to be always pulling latest of @types/node, when that might not be compatible with `typescript 3.9.10`.

### References

- #0000

**Comment by ansgarm** [comment]
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64262

**Comment by dev-robasi** [comment]
I am currently having this issue with `cdktf get`, Thinking of using self-hosted runners.

**Comment by akhsiM** [comment]
I encountered this issue when running `cdktf get` as well.

We got our deployment running by implementing the workaround mentioned above, which was to install `types/node@17.0.41`, in combination with switching from a global installation to an installation to the current project directory.

**Comment by dennisbrouwer91** [comment]
> I encountered this issue when running `cdktf get` as well.
> 
> We got our deployment running by implementing the workaround mentioned above, which was to install `types/node@17.0.41`, in combination with switching from a global installation to an installation to the current project directory.

What do you exactly mean with `witching from a global installation to an installation to the current project ` ?

**Comment by akhsiM** [comment]
> What do you exactly mean with `witching from a global installation to an installation to the current project ` ?

Within the docker image I was building, `cdktf` was installed globally. When I tried installing `types/node@17.0.41` globally, in an effort to deal with the issue here, I ran into some dependency issues with a package called `IdealTree` 🤷🏻 .

Switching to an installation that downloads the packages into a `node_modules` folder within the current directory got me past the aforementioned dependency issue.

**Comment by ansgarm** [comment]
Thanks for describing your workaround, @akhsiM 👍 Appreciated!

In case you haven't seen: We've released CDKTF 0.15.4 yesterday which should fix this: https://github.com/hashicorp/terraform-cdk/releases/tag/v0.15.4

**Comment by schapirama** [comment]
Working great! Thanks!

**Comment by ansgarm** [comment]
Cool! Let me close this then. Don't hesitate to file a new issue if anything might still feel off!
