### ISSUE TITLE
Trying to filter a AWS Subnet IDs -  TypeError: 'DataAwsSubnetIds' object is not subscriptable

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform-cdk#2619]
I am trying to build an instance with a specific subnet

```python
        subnets = DataAwsSubnetIds(self, 'subnets',
            vpc_id = "MY-VPC-ID",
            filter           = [{
               "name"   : "tag:Name",
               "values" : ["subnet-*-frontend"]
            }] 
      )

      TerraformOutput(self, "subnets_output", value=Fn.lookup(Fn.element(subnets.ids, 0), "subnet_id", "default"))
   ```

I get the following error:

```
  Synthesizing
[2023-02-08T14:58:08.912] [ERROR] default - Traceback (most recent call last):
  File "/Users/USER1/repos/cdktf/aws-codebuild/main.py", line 53, in <module>
    MyStack(app, "aws-codebuild")
  File "/Users/USER1/.local/share/virtualenvs/.config-OK2aWC4L/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/USER1/repos/cdktf/aws-codebuild/main.py", line 49, in __init__
    TerraformOutput(self, "subnets_output", value=subnets[0])
ERROR: cdktf encountered an error while synthesizing

Synth command: pipenv run python main.py
Error:         non-zero exit code 1

Command output on stderr:

    Traceback (most recent call last):
      File "/Users/USER1/repos/cdktf/aws-codebuild/main.py", line 53, in <module>
        MyStack(app, "aws-codebuild")
      File "/Users/USER1/.local/share/virtualenvs/.config-OK2aWC4L/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/Users/USER1/repos/cdktf/aws-codebuild/main.py", line 49, in __init__
        TerraformOutput(self, "subnets_output", value=subnets[0])
    TypeError: 'DataAwsSubnetIds' object is not subscriptable
```

Is there an example on how to query a VPC or Subnet based on filters?

**Comment by sbkg0002** [comment]
Your `subnets` definition is fine. AFAIK, just use `subnets.ids` to get the list of subnets.

**Comment by lmayorga1980** [comment]
I tried the following approach...

``` python
       ...
        subnets = DataAwsSubnetIds(self, 'subnets',
            vpc_id = "MY-VPC-ID",
            filter           = [{
               "name"   : "tag:Name",
               "values" : ["subnet-*-xyz"]
            }])

       instance = Instance(self, "compute",
                             ami=ami.id,
                             instance_type=instance_type,
                             key_name = "MY-KEY-NAME",
                             security_groups = security_groups,
                             #TODO: Find a better way to query subnet
                             subnet_id = Fn.element(Token.as_list(subnets.ids), 0)
        )
```

I am not sure if `Fn.element(Token.as_list(subnets.ids),0)` is the best way...

**Comment by sbkg0002** [comment]
Why not `subnets.ids[0]`?

**Comment by ansgarm** [comment]
`Fn.element(Token.as_list(subnets.ids),0)` is the best way, if you want to get the first item from that list 👍

Accessing the index won't work, as it is unknown at synth-time how many items are going to be in that list – that's also why CDKTF will throw an error if you attempt to as a safeguard.
