### ISSUE TITLE
Unable to convert for_each with map

### ISSUE THREAD

**Issue by mutahhir** [hashicorp/terraform-cdk#2634]
### Source HCL:

```hcl
resource "aws_instance" "changeme_aws_instance_count_foreach" {
  # Documentation: https://www.terraform.io/docs/language/meta-arguments/for_each.html
  for_each = {
    "a" = "1"
    "b" = "2"
  }

  tags = {
    Name = "aws_resource_count_${each.key}${each.value}"
  }
  instance_type = "t2.nano"
  ami           = "ami-0ddbdea833a8d2f0d"
}
```

### Error

```
Error: Internal Error: Property value expected type of string but got object
    at Object.Internal (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cmds/handlers.js:32403:17)
    at Object.convert (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cmds/handlers.js:153281:35)
    at async Command.handleCommand (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf.js:25292:9)
    at async BaseCommand.handler (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf.js:25125:13)
Collecting Debug Information...
/Users/mutahhir/src/hc/terraform-cdk/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Internal Error: Property value expected type of string but got object
    at Object.Internal (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cmds/handlers.js:32403:17)
    at Object.convert (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cmds/handlers.js:153281:35)
    at async Command.handleCommand (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf.js:25292:9)
    at async BaseCommand.handler (/Users/mutahhir/src/hc/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf.js:25125:13) {
  language: 'typescript',
  __type: 'Internal'
}

Node.js v18.12.1
```

**Comment by DanielMSchmidt** [comment]
Closed in #2732
