### ISSUE TITLE
Python sometimes introduces a newline which is invalid

### ISSUE THREAD

**Issue by mutahhir** [hashicorp/terraform-cdk#2641]
```py
        aws_rds_cluster_changeme_aws_aurora_cluster_instance =
        aws.rds_cluster.RdsCluster(self, "changeme_aws_aurora_cluster_instance",
            master_password=changeme_aws_aurora_cluster_password.value,
            master_username=changeme_aws_aurora_cluster_username.value,
            skip_final_snapshot=True
        )
```

### Error

```
Command output on stderr:

    Traceback (most recent call last):
      File "/Users/mutahhir/src/scratchpad/terraform-convert-examples/converted-langs/python/aws/main.py", line 6, in <module>
        from aws_db_instance.restore_db_from_snapshot.main import MyStack as aws_db_instance_restore_db_from_snapshot
      File "/Users/mutahhir/src/scratchpad/terraform-convert-examples/converted-langs/python/aws/aws_db_instance/restore_db_from_snapshot/main.py", line 43
        data_aws_db_snapshot_changeme_latest_prod_snapshot =
                                                            ^
    SyntaxError: invalid syntax
```

**Comment by mutahhir** [comment]
JSII Issue: https://github.com/aws/jsii/issues/3968
