### ISSUE TITLE
Convert should use CDKTF library types / Terraform meta-properties like it uses the schema

### ISSUE THREAD

**Issue by mutahhir** [hashicorp/terraform-cdk#2642]
### Source 

```hcl
# Documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot
# Explanation: Run a backup snapshot from prod Database. It uses timeouts for waiting until the snapshot operation complete
resource "aws_db_snapshot" "changeme_db_prod_snapshot" {
  db_instance_identifier = aws_db_instance.changeme_aws_db_instance_prod.id
  db_snapshot_identifier = "changeme-prod-snapshot"
  timeouts {
    read = "10m"
  }

  depends_on = [
    aws_db_instance.changeme_aws_db_instance_prod
  ]

}
```

### Synthed

```ts
const awsDbSnapshotChangemeDbProdSnapshot = new aws.dbSnapshot.DbSnapshot(
  this,
  "changeme_db_prod_snapshot",
  {
    dbInstanceIdentifier: awsDbInstanceChangemeAwsDbInstanceProd.id,
    dbSnapshotIdentifier: "changeme-prod-snapshot",
    depends_on: [`\${${awsDbInstanceChangemeAwsDbInstanceProd.fqn}}`],
    timeouts: [
      {
        read: "10m",
      },
    ],
  }
);
```

On Python, we wrap the value of depends_on with an fqn template string, which is also wrong:

```py
    depends_on=[f"${{{awsDbSnapshotChangemeDbProdSnapshot.fqn}}}"],
# Should've been
    depends_on=[awsDbSnapshotChangemeDbProdSnapshot],
```

### Source

```hcl
# Documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance
# Explanation: Use the latest production snapshot to create a DEV instance DB.
resource "aws_db_instance" "changeme_db_dev" {
  instance_class      = "db.t2.micro"
  identifier          = "changeme-db-from-backup"
  snapshot_identifier = data.aws_db_snapshot.changeme_latest_prod_snapshot.id
  skip_final_snapshot = true

  lifecycle {
    ignore_changes = [snapshot_identifier]
  }
}
```

### Converted

```py
        aws_db_instance_changeme_db_dev = aws.db_instance.DbInstance(self, "changeme_db_dev",
            identifier="changeme-db-from-backup",
            instance_class="db.t2.micro",
            skip_final_snapshot=True,
            snapshot_identifier=data_aws_db_snapshot_changeme_latest_prod_snapshot.id
        )
        aws_db_instance_changeme_db_dev.add_override("lifecycle", [
            ignore_changes=["${snapshot_identifier}"]
        
        ])
```

### Error

```
 Traceback (most recent call last):
      File "/Users/mutahhir/src/scratchpad/terraform-convert-examples/converted-langs/python/aws/main.py", line 6, in <module>
        from aws_db_instance.restore_db_from_snapshot.main import MyStack as aws_db_instance_restore_db_from_snapshot
      File "/Users/mutahhir/src/scratchpad/terraform-convert-examples/converted-langs/python/aws/aws_db_instance/restore_db_from_snapshot/main.py", line 55
        ignore_changes=["${snapshot_identifier}"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
```

**Comment by mutahhir** [comment]
## Timeouts

### Source

```hcl
# Project Service
# Documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service
resource "google_project_service" "changeme_project_service" {
  service = "compute.googleapis.com"

  timeouts {
    create = "30m"
    update = "40m"
  }

  disable_dependent_services = false
  disable_on_destroy         = false
}
```

### Converted

```ts
    new google.projectService.ProjectService(this, "changeme_project_service", {
      disableDependentServices: false,
      disableOnDestroy: false,
      service: "compute.googleapis.com",
      timeouts: [
        {
          create: "30m",
          update: "40m",
        },
      ],
    });
```

(Different from above snippet)
```py
        aws_db_snapshot_changeme_db_prod_snapshot = aws.db_snapshot.DbSnapshot(self, "changeme_db_prod_snapshot",
            db_instance_identifier=aws_db_instance_changeme_aws_db_instance_prod.id,
            db_snapshot_identifier="changeme-prod-snapshot",
            depends_on=[f"${{{aws_db_instance_changeme_aws_db_instance_prod.fqn}}}"],
            timeouts=[{
                "read": "10m"
            }
            ]
        )
```

The Type is not specified as a list, so I'm unsure where this is coming from.
