### ISSUE TITLE
Conversion from Typescript template literals and concatenated strings to other languages is broken

### ISSUE THREAD

**Issue by mutahhir** [hashicorp/terraform-cdk#2643]
### Converted

1. Reference a property via fqn better
```py
            availability_zone=f"\\${{dataAwsAvailabilityZonesChangemeAzListEbsSnapshot.names.fqn}[0]}",
```

2. Should not be using terraform escape here?
```py
        aws_iam_role_changeme_spot_and_fargate_iam_role_node_group = aws.iam_role.IamRole(self, "changeme_spot_and_fargate_iam_role_node_group",
# ...
            name=f"\\${{changemeSpotAndFargateName.value}}-eks-node-group-role"
        )
```

3. Just generally using the hcl literal escapes wrong
```py
            availability_zone=f"\\${element({changemeSpotAndFargateAvailabilityZones.value}, count.index)}",
```

4. More complex example
```py
    source_code_hash=f"${{filebase64sha256(\}"\\${{changemeLambdaFunctionZip.value}}\")}"
```

### Error

```

    Traceback (most recent call last):
      File "/Users/mutahhir/src/scratchpad/terraform-convert-examples/converted-langs/python/aws/main.py", line 11, in <module>
        from aws_ebs_volume.ebs_snapshot.main import MyStack as aws_ebs_volume_ebs_snapshot
      File "/Users/mutahhir/src/scratchpad/terraform-convert-examples/converted-langs/python/aws/aws_ebs_volume/ebs_snapshot/main.py", line 26
        availability_zone=f"\\${{dataAwsAvailabilityZonesChangemeAzListEbsSnapshot.names.fqn}[0]}",
                                                                                                  ^
    SyntaxError: f-string: single '}' is not allowed
```

### Correct way

```py
            availability_zone=f"${{{dataAwsAvailabilityZonesChangemeAzListEbsSnapshot.fqn}.names[0]}}",
```

---

## CSharp

```cs
            awsRouteTableChangemeSpotAndFargateRouteTablePrivate.AddOverride("count", $"\\${length({changemeSpotAndFargatePrivateSubnets.value})}");
```

When it should be:

```cs
            awsRouteTableChangemeSpotAndFargateRouteTablePrivate.AddOverride("count", $"\\${{length({changemeSpotAndFargatePrivateSubnets.value})}}");
```

It _shouldn't_ even need to escape the dollar sign, so even `$"${{length...` should work too?

**Comment by mutahhir** [comment]
JSII Issue: https://github.com/aws/jsii/issues/3967

**Comment by mutahhir** [comment]
Going to mark this as a non-blocker since the release of #2744 as that PR moves away from using string templates and on to string concatenation instead.

**Comment by ansgarm** [comment]
Wellllll, there's a now string concatenation problem in Python 😂
```
      File "/Users/ansgar/projects/playground/test-cdktf-convert/main.py", line 30, in __init__
        "description": "changeme-aws-security-group-dynamic-ingress-${" + aws_security_group_changeme_aws_security_group_dynamic_dynamic_iterator0.key + "}",
    TypeError: can only concatenate str (not "_LazyBaseProxy") to str
```
(more context in the original comment: https://github.com/hashicorp/terraform-cdk/issues/2637#issuecomment-1505210351)
