### ISSUE TITLE
yarn package requires wheel and twine python packages

### ISSUE THREAD

**Issue by cmclaughlin** [hashicorp/terraform-cdk#269]
Not sure if this is a `terraform-cdk` issue... or perhaps the problem is in one of the dependancies such as `jsii-pacmak`?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf master branch
terraform 0.12.29
python 3.8.x

### Affected Resource(s)

`yarn package`

### Expected Behavior

run `yarn package` w/o errors

### Debug Output

```
$ pyenv shell 3.8.1
(3.8.1) cmclaughlin-local@cm in /private/tmp/cdk-playground/terraform-cdk
on master
$ pyenv virtualenv cdktf-playground-3.8.1
Looking in links: /var/folders/pw/v0cjf_4967q409vfpwg0v3140000gp/T/tmp4wxgwcwo
Requirement already satisfied: setuptools in /Users/cmclaughlin-local/.pyenv/versions/3.8.1/envs/cdktf-playground-3.8.1/lib/python3.8/site-packages (41.2.0)
Requirement already satisfied: pip in /Users/cmclaughlin-local/.pyenv/versions/3.8.1/envs/cdktf-playground-3.8.1/lib/python3.8/site-packages (19.2.3)
(3.8.1) cmclaughlin-local@cm in /private/tmp/cdk-playground/terraform-cdk
on master
$ pyenv activate cdktf-playground-3.8.1
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /private/tmp/cdk-playground/terraform-cdk
on master
$ cd /tmp/cdk-playground/
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground
$ git clone git@github.com:hashicorp/terraform-cdk.git
Cloning into 'terraform-cdk'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 3385 (delta 6), reused 10 (delta 3), pack-reused 3368
Receiving objects: 100% (3385/3385), 4.12 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (2092/2092), done.
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground
$ cd terraform-cdk/
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground/terraform-cdk
on master
$ yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > cdktf@0.0.0" has unmet peer dependency "constructs@^3.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 7.25s.
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground/terraform-cdk
on master
$ yarn build && yarn package
yarn run v1.22.4
$ lerna run build
lerna notice cli v3.22.1
lerna info Executing command in 13 packages: "yarn run build"
lerna info run Ran npm script 'build' in 'cdktf' in 4.5s:
$ jsii
lib/backends/etcdv3-backend.ts:20:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.

20     readonly lock?: boolean;
                ~~~~
lib/backends/consul-backend.ts:23:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.

23     readonly lock?: boolean;
                ~~~~
lerna info run Ran npm script 'build' in 'cdktf-cli' in 4.6s:
$ tsc
lerna info run Ran npm script 'build' in 'demo-cdktf-ts-docker' in 13.1s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-vault' in 31.2s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-kubernetes' in 49.6s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-google' in 53.2s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-azure' in 53.5s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-azurerm' in 83.3s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-gcs' in 74.5s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-remote' in 68.0s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-s3' in 51.0s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'aws' in 102.3s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-aws-cloudfront-proxy' in 102.9s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna success run Ran npm script 'build' in 13 packages in 112.0s:
lerna success - typescript-aws-cloudfront-proxy
lerna success - aws
lerna success - typescript-azure
lerna success - demo-cdktf-ts-docker
lerna success - typescript-google
lerna success - typescript-kubernetes
lerna success - typescript-vault
lerna success - typescript-backends-azurerm
lerna success - typescript-backends-gcs
lerna success - typescript-backends-remote
lerna success - typescript-backends-s3
lerna success - cdktf-cli
lerna success - cdktf
✨  Done in 112.68s.
yarn run v1.22.4
$ lerna run package && tools/collect-dist.sh
lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "yarn run package"
lerna ERR! yarn run package exited 1 in 'cdktf'
lerna ERR! yarn run package stdout:
$ jsii-pacmak
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run package stderr:
Error: Process exited with status 1

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

    at ChildProcess.<anonymous> (/private/tmp/cdk-playground/terraform-cdk/packages/cdktf/node_modules/jsii-pacmak/lib/util.js:57:31)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
error Command failed with exit code 1.

lerna ERR! yarn run package exited 1 in 'cdktf'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground/terraform-cdk
on master
$ pip install wheel
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.34.2
WARNING: You are using pip version 19.2.3, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground/terraform-cdk
on master
$ yarn build && yarn package
yarn run v1.22.4
$ lerna run build
lerna notice cli v3.22.1
lerna info Executing command in 13 packages: "yarn run build"
lerna info run Ran npm script 'build' in 'cdktf' in 4.4s:
$ jsii
lib/backends/etcdv3-backend.ts:20:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.

20     readonly lock?: boolean;
                ~~~~
lib/backends/consul-backend.ts:23:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.

23     readonly lock?: boolean;
                ~~~~
lerna info run Ran npm script 'build' in 'cdktf-cli' in 4.5s:
$ tsc
lerna info run Ran npm script 'build' in 'typescript-vault' in 19.9s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'demo-cdktf-ts-docker' in 24.6s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-kubernetes' in 30.1s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-google' in 32.0s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-azurerm' in 34.5s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-aws-cloudfront-proxy' in 43.3s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-azure' in 43.7s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-gcs' in 24.5s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'aws' in 44.8s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-remote' in 23.4s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-s3' in 20.6s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna success run Ran npm script 'build' in 13 packages in 59.6s:
lerna success - typescript-aws-cloudfront-proxy
lerna success - aws
lerna success - typescript-azure
lerna success - demo-cdktf-ts-docker
lerna success - typescript-google
lerna success - typescript-kubernetes
lerna success - typescript-vault
lerna success - typescript-backends-azurerm
lerna success - typescript-backends-gcs
lerna success - typescript-backends-remote
lerna success - typescript-backends-s3
lerna success - cdktf-cli
lerna success - cdktf
✨  Done in 60.10s.
yarn run v1.22.4
$ lerna run package && tools/collect-dist.sh
lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "yarn run package"
lerna ERR! yarn run package exited 1 in 'cdktf'
lerna ERR! yarn run package stdout:
$ jsii-pacmak
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run package stderr:
Error: Process exited with status 127

pyenv: twine: command not found

The `twine' command exists in these Python versions:
  3.8.2/envs/aws-toolkit-3.8.2
  3.8.2/envs/cdktf
  3.8.2/envs/cdktf-playground
  aws-toolkit-3.8.2
  cdktf
  cdktf-playground

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

    at ChildProcess.<anonymous> (/private/tmp/cdk-playground/terraform-cdk/packages/cdktf/node_modules/jsii-pacmak/lib/util.js:57:31)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
error Command failed with exit code 1.

lerna ERR! yarn run package exited 1 in 'cdktf'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground/terraform-cdk
on master
$ pip install twine
Collecting twine
  Using cached https://files.pythonhosted.org/packages/ad/db/b2c65078b783c6694bdfa0911bbbe0e2be7fcbc98ff23a99b8be544906b6/twine-3.2.0-py3-none-any.whl
Collecting readme-renderer>=21.0 (from twine)
  Using cached https://files.pythonhosted.org/packages/54/e4/ed43056d80a4fcc3667e543a59cc6beaf0a3c0eade837e5591e82ad3c25a/readme_renderer-26.0-py2.py3-none-any.whl
Collecting pkginfo>=1.4.2 (from twine)
  Using cached https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
Collecting rfc3986>=1.4.0 (from twine)
  Using cached https://files.pythonhosted.org/packages/78/be/7b8b99fd74ff5684225f50dd0e865393d2265656ef3b4ba9eaaaffe622b8/rfc3986-1.4.0-py2.py3-none-any.whl
Collecting requests>=2.20 (from twine)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting keyring>=15.1 (from twine)
  Using cached https://files.pythonhosted.org/packages/a8/5e/d13b9feb235d042321a239ac8bc85e90cf3bbe49090c6f1383ac3fd53e0e/keyring-21.2.1-py3-none-any.whl
Requirement already satisfied: setuptools>=0.7.0 in /Users/cmclaughlin-local/.pyenv/versions/3.8.1/envs/cdktf-playground-3.8.1/lib/python3.8/site-packages (from twine) (41.2.0)
Collecting colorama>=0.4.3 (from twine)
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting tqdm>=4.14 (from twine)
  Using cached https://files.pythonhosted.org/packages/af/88/7b0ea5fa8192d1733dea459a9e3059afc87819cb4072c43263f2ec7ab768/tqdm-4.48.0-py2.py3-none-any.whl
Collecting requests-toolbelt!=0.9.0,>=0.8.0 (from twine)
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting bleach>=2.1.0 (from readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/9a/1e/7d6cb3b27cd2c490558349ca5d5cc05b390b017da1c704cac807ac8bd9fb/bleach-3.1.5-py2.py3-none-any.whl
Collecting six (from readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting docutils>=0.13.1 (from readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/81/44/8a15e45ffa96e6cf82956dd8d7af9e666357e16b0d93b253903475ee947f/docutils-0.16-py2.py3-none-any.whl
Collecting Pygments>=2.5.1 (from readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.20->twine)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.20->twine)
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests>=2.20->twine)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests>=2.20->twine)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting webencodings (from bleach>=2.1.0->readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting packaging (from bleach>=2.1.0->readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->bleach>=2.1.0->readme-renderer>=21.0->twine)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Installing collected packages: six, webencodings, pyparsing, packaging, bleach, docutils, Pygments, readme-renderer, pkginfo, rfc3986, certifi, urllib3, idna, chardet, requests, keyring, colorama, tqdm, requests-toolbelt, twine
Successfully installed Pygments-2.6.1 bleach-3.1.5 certifi-2020.6.20 chardet-3.0.4 colorama-0.4.3 docutils-0.16 idna-2.10 keyring-21.2.1 packaging-20.4 pkginfo-1.5.0.1 pyparsing-2.4.7 readme-renderer-26.0 requests-2.24.0 requests-toolbelt-0.9.1 rfc3986-1.4.0 six-1.15.0 tqdm-4.48.0 twine-3.2.0 urllib3-1.25.10 webencodings-0.5.1
WARNING: You are using pip version 19.2.3, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cdktf-playground-3.8.1) cmclaughlin-local@cm in /tmp/cdk-playground/terraform-cdk
on master
$ yarn build && yarn package
yarn run v1.22.4
$ lerna run build
lerna notice cli v3.22.1
lerna info Executing command in 13 packages: "yarn run build"
lerna info run Ran npm script 'build' in 'cdktf' in 4.3s:
$ jsii
lib/backends/etcdv3-backend.ts:20:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.

20     readonly lock?: boolean;
                ~~~~
lib/backends/consul-backend.ts:23:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.

23     readonly lock?: boolean;
                ~~~~
lerna info run Ran npm script 'build' in 'cdktf-cli' in 4.4s:
$ tsc
lerna info run Ran npm script 'build' in 'demo-cdktf-ts-docker' in 27.3s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-vault' in 32.0s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-kubernetes' in 33.8s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-azure' in 37.2s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-azurerm' in 37.1s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-google' in 40.5s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-aws-cloudfront-proxy' in 42.4s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-gcs' in 21.4s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'aws' in 50.0s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-s3' in 17.4s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna info run Ran npm script 'build' in 'typescript-backends-remote' in 20.5s:
$ yarn get && tsc
$ cdktf get
Generated typescript constructs in the output directory: .gen
lerna success run Ran npm script 'build' in 13 packages in 61.3s:
lerna success - typescript-aws-cloudfront-proxy
lerna success - aws
lerna success - typescript-azure
lerna success - demo-cdktf-ts-docker
lerna success - typescript-google
lerna success - typescript-kubernetes
lerna success - typescript-vault
lerna success - typescript-backends-azurerm
lerna success - typescript-backends-gcs
lerna success - typescript-backends-remote
lerna success - typescript-backends-s3
lerna success - cdktf-cli
lerna success - cdktf
✨  Done in 61.77s.
yarn run v1.22.4
$ lerna run package && tools/collect-dist.sh
lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "yarn run package"
lerna info run Ran npm script 'package' in 'cdktf' in 3.8s:
$ jsii-pacmak
lerna info run Ran npm script 'package' in 'cdktf-cli' in 0.9s:
$ ./package.sh
lerna success run Ran npm script 'package' in 2 packages in 4.8s:
lerna success - cdktf-cli
lerna success - cdktf
collecting from /private/tmp/cdk-playground/terraform-cdk/packages/cdktf-cli/dist
collecting from /private/tmp/cdk-playground/terraform-cdk/packages/cdktf/dist
dist/
dist//python
dist//python/cdktf-0.0.0-py3-none-any.whl
dist//python/cdktf-0.0.0.tar.gz
dist//js
dist//js/cdktf-cli-0.0.0.tgz
dist//js/cdktf@0.0.0.jsii.tgz
✨  Done in 6.10s.
```

**Comment by skorfmann** [comment]
@cmclaughlin Is this still an issue? If so, could you provide a bit more context since it looks like it's related to the local setup.

**Comment by cmclaughlin** [comment]
Yes, I can still reproduce this...

Twine is not installed in Python environments by default. But it's needed for `yarn package`. 

I can certainly add `pip install twine` to the docs, but it seems like it should be automated... and/or if jsii requires twine, perhaps the fix should be there? Grepping my `node_modules/jsii-pacmak` does show some commands that should install twine, but I'm not sure if that's related or not.
