### ISSUE TITLE
Dictionary keys should work snake cased

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- Python

### Affected Resource(s)

- `KubernetesDeployment`
- Probably all Python resources 

```python
#!/usr/bin/env python
from constructs import Construct
from cdktf import App, TerraformStack
from gen.kubernetes import KubernetesProvider, Namespace, Deployment, Service

class KubeStack(TerraformStack):
    def __init__(self, scope, id):
        super().__init__(scope, id)

        KubernetesProvider(self, "kind")

        example_namespace = Namespace(self, "tf-cdk-example",
            metadata=[{
                "name": "tf-cdk-example"
            }]
        )

        app = "nginx-example"
        Deployment(self, "nginx-deployment",
            metadata=[{
                "name": app,
                "namespace": example_namespace.metadata[0].name,
                "labels": {
                    "app": app
                }
            }],
            spec=[{
                "replicas": 2,
                "selector": [{
                    "match_labels": {
                        "app": app
                    }
                }],
                "template": [{
                    "metadata": [{
                        "labels": {
                            "app": app
                        }
                    }],
                    "spec": [{
                        "container": [{
                            "image": "nginx:1.7.8",
                            "name": "example",
                            "port": [{
                                "container_port": 80
                            }],
                            "resources": [{
                                "limits": [{
                                    "cpu": "0.5",
                                    "memory": "512Mi"
                                }],
                                "requests": [{
                                    "cpu": "250m",
                                    "memory": "50Mi"
                                }]
                            }]
                        }]
                    }]
                }]
            }]
        )

        Service(self, "nginx-service",
            metadata=[{
                "name": app
            }],
            spec=[{
                "selector": {
                    "app": app
                },
                "port": [{
                    "node_port": 30201,
                    "port": 80,
                    "target_port": "80"
                }],
                "type": "NodePort"
            }]
        )

app = App()
KubeStack(app, "tf-cdk-example")
app.synth()
```

### Debug Output

```
pipenv run ./main.py
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Warning: Your Pipfile requires python_version 3.7, but you are using 3.8.5 (/Users/s/.local/share/v/a/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
jsii.errors.JavaScriptError:
  Error: Missing required properties for kubernetes.DeploymentSpecTemplateSpecContainerPort: containerPort
      at validateRequiredProps (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7281:15)
      at Object.deserialize (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6941:21)
      at Kernel._toSandbox (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8304:61)
      at /Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6833:42
      at Array.map (<anonymous>)
      at Object.deserialize (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6833:26)
      at Kernel._toSandbox (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8304:61)
      at /Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6947:29
      at mapValues (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7219:27)
      at Kernel._wrapSandboxCode (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8398:19)
      at Kernel._create (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7922:26)
      at Kernel.create (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7666:21)
      at KernelHost.processRequest (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7446:28)
      at KernelHost.run (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7384:14)
      at Immediate._onImmediate (/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7387:37)
      at processImmediate (internal/timers.js:456:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 81, in <module>
    KubeStack(app, "tf-cdk-example")
  File "/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "./main.py", line 19, in __init__
    Deployment(self, "nginx-deployment",
  File "/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/sebastian/projects/cdk/terraform-cdk/examples/python/aws/gen/kubernetes/__init__.py", line 24259, in __init__
    jsii.create(Deployment, self, [scope, id, config])
  File "/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 224, in create
    response = self.provider.create(
  File "/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Users/sebastian/.local/share/virtualenvs/aws-VKNxKHLM/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Missing required properties for kubernetes.DeploymentSpecTemplateSpecContainerPort: containerPort
```

### Expected Behavior

It should synthesize with snake cased keys in dictionaries

### Actual Behavior

The keys `match_labels` and `container_port` are only working when camel cased `matchLabels` and `containerPort`

**Comment by skorfmann** [comment]
Similar issue as this one https://github.com/hashicorp/terraform-cdk/issues/253#issuecomment-665882983

There's probably nothing we can do about this right now.
