### ISSUE TITLE
Getting "A system error occurred: uv_os_get_passwd returned ENOENT" when 

### ISSUE THREAD

**Issue by toha-nordic** [hashicorp/terraform-cdk#2825]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.15.5 and 0.16.0 with Typescript. NodeJS v18.16.0.

### Affected Resource(s)

cdktf init prints out errors and cdktf deploy fails to execute.

### Debug Output

https://gist.github.com/toha-nordic/194ec10412d6250f2d1265660387f785

### Expected Behavior

cdktf runs without errors.

### Actual Behavior
```
cdktf deploy
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (node:internal/errors:250:5)
    at new NodeError (node:internal/errors:361:7)
    at Object.userInfo (node:os:366:11)
    at sbt (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:90:18445)
    at z9e (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:90:19575)
    at /home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:208:13079
    at e.configureScope (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:13:13455)
    at td (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:78:19214)
    at Object.w8t (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:78:19818)
    at pmr (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:208:13022)
Collecting Debug Information...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (node:internal/errors:250:5)
    at new NodeError (node:internal/errors:361:7)
    at Object.userInfo (node:os:366:11)
    at sbt (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:90:18445)
    at z9e (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:90:19575)
    at /home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:208:13079
    at e.configureScope (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:13:13455)
    at td (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:78:19214)
    at Object.w8t (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:78:19818)
    at pmr (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.16.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:208:13022)
(node:2968685) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
(Use `node --trace-warnings ...` to show where the warning was created)
Debug Information:
language: typescript
cdktf-cli: 0.16.0
node: v18.16.0
cdktf: 0.15.5
constructs: 10.2.0
jsii: null
terraform: 1.4.5
arch: x64
os: linux 5.15.0-67-generic
```
And init:
```
cdktf init --template=typescript --providers=kreuzwerker/docker --local
Could not run version check - A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.<STACK NAME>.tfstate' in the root of your project.
? Project Name tmp
? Project Description A simple getting started project for cdktf.
? Do you want to start from an existing Terraform project? No
? Do you want to send crash reports to the CDKTF team? Refer to 
https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/configuration-file#enable-crash-reporting-for-the-cli for more information Yes

added 2 packages, and audited 57 packages in 2s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 301 packages, and audited 358 packages in 11s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
========================================================================================================

  Your cdktf typescript project is ready!

  cat help                Print this message

  Compile:
    npm run get           Import/update Terraform providers and modules (you should check-in this directory)
    npm run compile       Compile typescript code to javascript (or "npm run watch")
    npm run watch         Watch for changes and compile typescript in the background
    npm run build         Compile typescript

  Synthesize:
    cdktf synth [stack]   Synthesize Terraform resources from stacks to cdktf.out/ (ready for 'terraform apply')

  Diff:
    cdktf diff [stack]    Perform a diff (terraform plan) for the given stack

  Deploy:
    cdktf deploy [stack]  Deploy the given stack

  Destroy:
    cdktf destroy [stack] Destroy the stack

  Test:
    npm run test        Runs unit tests (edit __tests__/main-test.ts to add your own tests)
    npm run test:watch  Watches the tests and reruns them on change

  Upgrades:
    npm run upgrade        Upgrade cdktf modules to latest version
    npm run upgrade:next   Upgrade cdktf modules to latest "@next" version (last commit)

 Use Providers:

  You can add prebuilt providers (if available) or locally generated ones using the add command:
  
  cdktf provider add "aws@~>3.0" null kreuzwerker/docker

  You can find all prebuilt providers on npm: https://www.npmjs.com/search?q=keywords:cdktf
  You can also install these providers directly through npm:

  npm install @cdktf/provider-aws
  npm install @cdktf/provider-google
  npm install @cdktf/provider-azurerm
  npm install @cdktf/provider-docker
  npm install @cdktf/provider-github
  npm install @cdktf/provider-null

  You can also build any module or provider locally. Learn more https://cdk.tf/modules-and-providers

========================================================================================================

Checking whether pre-built provider exists for the following constraints:
  provider: kreuzwerker/docker
  version : latest
  language: typescript
  cdktf   : 0.16.0

Found pre-built provider.
Adding package @cdktf/provider-docker @ 7.0.0
Installing package @cdktf/provider-docker @ 7.0.0 using npm.
Package installed.
[2023-04-20T09:35:17.444] [ERROR] default - Could not send telemetry data: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
```

### Steps to Reproduce

Im running on Ubuntu 20.04.06 LTS with 5.15.0-67-generic kernel. NodeJS v18.16.0, Terraform 1.4.5.

### Important Factoids

My guess is that the error is due to this local laptop user not having an entry in /etc/passwd file. The user is provisioned from corporate MS Active Directory service via local realmd+sssd services. I believe this is common configuration in corporate environments.

### References

- #0000

**Comment by ansgarm** [comment]
Hi @toha-nordic 👋

Thank you for the bug report! It seems like the environment you're running in doesn't make it possible for the CDKTF CLI to determine a user home directory using `os.userInfo()` from Node.js.

However, you should be able to work around this by setting the `CDKTF_HOME` environment variable.

We should at least print a better error message if this call fails (e.g. hinting at `CDKTF_HOME`) 🤔
