### ISSUE TITLE
Error: [select prompt] No selectable choices. All choices are disabled.

### ISSUE THREAD

**Issue by nosayana** [hashicorp/terraform-cdk#2982]
### Expected Behavior

While running cdktf init --template="typescript" a terraform cloud project directory should have been initialized.

### Actual Behavior

Error: [select prompt] No selectable choices. All choices are disabled.
    at C:\Users\redacted\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:460:259
    at Ki (C:\Users\redacted\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:454:522)
    at C:\Users\redacted\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:460:216
    at C (C:\Users\redacted\AppData\Roaming\npm\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:454:1793)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Steps to Reproduce

1. npm install -g typescript
2. npm install -g cdktf-cli
3. cdktf init --template="typescript"

### Versions

language: null
cdktf-cli: 0.17.0
node: v18.16.1
terraform: 1.5.1
arch: x64
os: win32 10.0.22621

### Possible Solutions

No

### Workarounds

No

### Anything Else?

No

### References

None

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
@mutahhir Is this fixed by the changes you did for the Terraform Cloud yes/no question?

**Comment by aroundaesthetics** [comment]
Same deal here:

```
$ cdktf --version
0.18.0
$ cdktf init
? What template do you want to use? typescript

Initializing a project using the typescript template.
? Project Name cloudflare
? Project Description Deploy websites to CloudFlare via terraform CDK
? Would you like to use Terraform Cloud? yes

Detected Terraform Cloud token.

We will now set up Terraform Cloud for your project.


[select prompt] No selectable choices. All choices are disabled.
```

**Comment by howdoicomputer** [comment]
I got this exact error running through the AWS tutorial. I ended up configuring it manually.

**Comment by DanielMSchmidt** [comment]
Do you have organisations in Terraform Cloud that you are part of?

**Comment by howdoicomputer** [comment]
@DanielMSchmidt I actually did not. I had created a Terraform Cloud (to try it out) but had not created an organization. Maybe the CLI can return a message when there are no valid organizations associated with the account? Would a PR be acceptable?

**Comment by DanielMSchmidt** [comment]
Yeah that would be great. A pr would be appreciated, thanks for your help!
