### ISSUE TITLE
[python-pip] Module in `cdktf.json` is not being installed correctly, with 'cdktf get' command

### ISSUE THREAD

**Issue by kination** [hashicorp/terraform-cdk#3026]
### Expected Behavior

By referring following: https://github.com/cdktf/docker-on-aws-ecs-with-terraform-cdk-using-typescript/blob/main/infrastructure/cdktf.json

I've setup `cdktf.json` as:
```
{
  "language": "python",
  "app": "python3 ./main.py",
  "projectId": "5f6d6bcb-daa6-4dae-9ae1-d02cd37c9f08",
  "sendCrashReports": "true",
  "terraformProviders": [],
  "terraformModules": [
    "terraform-aws-modules/vpc/aws@5.0.0",
    "terraform-aws-modules/rds/aws@5.0.0"
  ],
  "codeMakerOutput": "imports",
  "context": {}
}
```

And this is `main.py` file
```
from imports.terraform_aws_modules.aws import Vpc
from imports.terraform_aws_modules.aws import Rds


class MyStack(TerraformStack):
...
```

It should success when running `cdktf diff`.

### Actual Behavior

Shows failure with following log
```
$ cdktf diff
...
[2023-07-22T20:58:49.628] [ERROR] default - Traceback (most recent call last):
  File "/Users/kination/workspace/private/rz-dev/rz-iac/./main.py", line 6, in <module>
    from imports.terraform_aws_modules.aws import Rds
ImportError: cannot import name 'Rds' from 'imports.terraform_aws_modules.aws' (/Users/kination/workspace/private/rz-dev/rz-iac/
ERROR: cdktf encountered an error while synthesizing

Synth command: python3 ./main.py
Error:         non-zero exit code 1

Command output on stderr:

    Traceback (most recent call last):
      File "/Users/kination/workspace/private/rz-dev/rz-iac/./main.py", line 6, in <module>
        from imports.terraform_aws_modules.aws import Rds
    ImportError: cannot import name 'Rds' from 'imports.terraform_aws_modules.aws' (/Users/kination/workspace/private/rz-dev/rz-iac/imports/terraform_aws_modules/aws/__init__.py)
```

Seems only vpc module has been installed, and rds has not.

### Steps to Reproduce

1. Run `cdktf init --template=python-pip --local`
2. Add following modules
```
  "terraformModules": [
    "terraform-aws-modules/vpc/aws@5.0.0",
    "terraform-aws-modules/rds/aws@5.0.0"
  ],
```
3. Run `cdktf get`
4. After install, run `cdktf diff`

### Versions

language: python
cdktf-cli: 0.0.0
node: v16.14.2
cdktf: 0.0.0 (master branch)
constructs: 10.2.69
jsii: 1.85.0
terraform: 1.4.2
arch: arm64
os: darwin 22.5.0 (MacOS M1)
python: Python 3.9.1
pip: null
pipenv: pipenv, version 2023.3.20

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kination** [comment]
I've tried same thing with typescript template.

[typescript]
<img width="302" alt="Screenshot 2023-07-23 at 10 56 35" src="https://github.com/hashicorp/terraform-cdk/assets/1720209/642bf2ad-8230-4f00-b789-d08ee65ebbce">

[python]
<img width="305" alt="Screenshot 2023-07-23 at 10 57 54" src="https://github.com/hashicorp/terraform-cdk/assets/1720209/8a928cbc-9615-44a0-814d-4f65278c51f5">

As you can see, `python-pip` only installs 1 module though there are 2 modules defined in `terraformModules`.

**Comment by jsteinich** [comment]
You could try a workaround by explicitly specifying properties in `cdkt.json`. Would look something like:
```json
"terraformModules": [
    {"source": "terraform-aws-modules/vpc/aws",
     "name": "vpc",
     "fqn": "terraform-aws-modules/vpc/aws",
     "version: "5.0.0",
     "namespace": "terraform-aws-modules/aws"
   },
    {"source": "terraform-aws-modules/rds/aws",
     "name": "rds",
     ...
   }
  ],
```

**Comment by kination** [comment]
@jsteinich I've tried with following...
```
  "terraformProviders": [
  ],
  "terraformModules": [
    {
      "source": "terraform-aws-modules/vpc/aws",
      "name": "vpc",
      "fqn": "terraform-aws-modules/vpc/aws",
      "version": "5.0.0",
      "namespace": "terraform-aws-modules/aws"
    },
    {
      "source": "terraform-aws-modules/rds/aws",
      "name": "rds",
      "fqn": "terraform-aws-modules/rds/aws",
      "version": "5.0.0",
      "namespace": "terraform-aws-modules/aws"
    }
  ],
```
but showing same issue...

**Comment by jsteinich** [comment]
Looks like changing the namespace so that they are different will generate both modules successfully.

**Comment by kination** [comment]
@jsteinich thanks! Seems this works well.
Until this has been resolved, it will be better to comment on document about this 👀

**Comment by Maed223** [comment]
Did some extra digging and found that the issue exists for C# and Java as well as Python. Seems that the problem has to do with how the provider generator resolves the path to the module and what name it uses for it. In Python it looks like both the `rds` and `vpc` module resolve to the path `terraform_aws_modules/aws`, the `vpc` module overwriting the folder contents where the `rds` module was previously present.

Annoying part is that all this is handled relative to the language used, which is why it isn't a problem in Typescript or Go.
