### ISSUE TITLE
DotNet Null Provider : Unhandled exception. System.Exception: Cannot find module '@cdktf/provider-null'

### ISSUE THREAD

**Issue by ankitatdnv** [hashicorp/terraform-cdk#3082]
### Expected Behavior

Null Resource should get created and execute a local executioner with a powershell script.

### Actual Behavior

Getting following Error when try to run cdktf deploy:

```
Unhandled exception. System.Exception: Cannot find module '@cdktf/provider-null'
    Require stack:
    - C:\Users\ankcho\AppData\Local\Temp\jsii-kernel-EY3jcW\node_modules\cdktf-jsii\services\test-app\main.js
    - C:\Users\ankcho\AppData\Local\Temp\jsii-kernel-EY3jcW\node_modules\cdktf-jsii\index.js
    - C:\Users\ankcho\AppData\Local\Temp\jsii-kernel-EY3jcW
       at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
       at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
       at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
       at Amazon.JSII.Runtime.Services.Client.Load(LoadRequest request)
       at Amazon.JSII.Runtime.Services.Client.Load(String name, String version, String tarball)
       at Amazon.JSII.Runtime.Services.Client.LoadPackage(String package, String version, String tarballPath)
       at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
       at Amazon.JSII.Runtime.Deputy.JsiiClassAttribute..ctor(Type nativeType, String fullyQualifiedName, String parametersJson)
       at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
       at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
       at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
       at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
       at Amazon.JSII.Runtime.Services.TypeCache.CacheTypes(Assembly assembly)
       at Amazon.JSII.Runtime.Services.TypeCache.Refresh()
       at Amazon.JSII.Runtime.Services.TypeCache.TryGetType[T](String fullyQualifiedName)
       at Amazon.JSII.Runtime.Services.TypeCache.TryGetClassType(String fullyQualifiedName)
       at Amazon.JSII.Runtime.Services.Converters.ValueConverter.<TryConvertCustomType>g__IsReferenceType|17_0(<>c__DisplayClass17_0& )
       at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCustomType(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, String fullyQualifiedName, Object& result)
       at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
       at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvert(IOptionalValue optionalValue, IReferenceMap referenceMap, Object value, Object& result)
       at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
       at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
       at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
       at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
       at Amazon.JSII.Runtime.Deputy.DeputyBase.ConvertArguments(Parameter[] parameters, Object[] arguments)
       at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
       at Constructs.Construct..ctor(DeputyProps props)
       at HashiCorp.Cdktf.TerraformStack..ctor(Construct scope, String id)
       at MyCompany.MyApp.MainStack..ctor(Construct scope, String id) in C:\Users\ankcho\source\repos\cdktf-app\MainStack.cs:line 14
       at MyCompany.MyApp.Program.Main(String[] args) in C:\Users\ankcho\source\repos\cdktf-app\Program.cs:line 12
```

### Steps to Reproduce

1. Write a custom Construct in Typescript using @cdktf/provider-null npm module, which create a local-exec resource to execute a powershell script.
2. Create a Nuget package using JSII to provide above mentioned construct as a Nuget library.
3. Use the above mentioned Nuget package in Dotnet project.
4. Run cdktf synth or cdktf deploy

### Versions

language: csharp
cdktf-cli: 0.17.0
node: v16.20.1
cdktf: 0.17.0
constructs: 10.2.69
jsii: 1.87.0
terraform: 1.5.2
arch: x64
os: win32 10.0.19045
dotnet: 7.0.304

### Providers

┌───────────────┬──────────────────┬─────────┬────────────┬───────────────────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name                      │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼───────────────────────────────────┼─────────────────┤
│ azuread       │ 2.41.0           │ ^0.17.0 │            │ HashiCorp.Cdktf.Providers.Azuread │ 9.0.1           │
├───────────────┼──────────────────┼─────────┼────────────┼───────────────────────────────────┼─────────────────┤
│ azurerm       │ 3.69.0           │ ^0.17.0 │            │ HashiCorp.Cdktf.Providers.Azurerm │ 9.0.7           │
├───────────────┼──────────────────┼─────────┼────────────┼───────────────────────────────────┼─────────────────┤
│ null          │ 3.2.1            │ ^0.17.0 │            │ HashiCorp.Cdktf.Providers.Null    │ 7.0.0           │

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ankitatdnv** [comment]
I was able to resolve the issue by adding @cdktf/provider-null as peer dependency while packaging using jsii. But I am not sure whether it is the correct behavior or not.

**Comment by DanielMSchmidt** [comment]
Adding a peer dependency is correct. This seems to be resolved, closing the issue 👍
