### ISSUE TITLE
cdktf: missing nodejs import

### ISSUE THREAD

**Issue by bitdean** [hashicorp/terraform-cdk#3129]
### Expected Behavior

cdktf get command should work

### Actual Behavior

```
cdktf get
Cannot find module 'functions-have-names'
Require stack:
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/set-function-name/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/implementation.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/deep-equal/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/coerceType.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/expressions.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/generation.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf
Error: Cannot find module 'functions-have-names'
Require stack:
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/set-function-name/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/implementation.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/deep-equal/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/coerceType.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/expressions.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/generation.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
Collecting Debug Information...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find module 'functions-have-names'
Require stack:
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/set-function-name/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/implementation.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/deep-equal/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/coerceType.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/expressions.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/generation.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js
- /usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/set-function-name/index.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/implementation.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/regexp.prototype.flags/index.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/deep-equal/index.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/coerceType.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/expressions.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/generation.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js',
    '/usr/local/lib/nodejs/node-v18.17.1/lib/node_modules/cdktf-cli/bundle/bin/cdktf'
  ]
}

Node.js v18.17.1

```

### Steps to Reproduce

`npm install --global --no-fund cdktf-cli@0.18.0`
in project run:
`cdktf get`

### Versions

cdktf-cli: 0.18.0
nodejs: v18.17.1
npm: 9.6.7

### Possible Solutions

Add missing dependency:
`npm install --global --no-fund functions-have-names`

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kenkku** [comment]
Caused by ljharb/set-function-name#1, which is being used in in `regexp.prototype.flags@1.5.1`, which is a dependency of `deep-equal`, and that comes from `@cdktf/hcl2cdk`. I believe this should be possible to work around by downgrading `regexp.prototype.flags` to 1.5.0.

**Comment by tiparega** [comment]
Any workaround? I saw this but not working:
https://github.com/ljharb/set-function-name/issues/1#issuecomment-1717166596
```
npm i -D functions-have-names
npm install --global cdktf-cli@latest
cdktf get --language java #Fails
```

**Comment by kenkku** [comment]
@tiparega you could try adding [an override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) for `regex.prototype.flags` in your `package.json`. Forcing it to `1.5.0` (problem was introduced in `1.5.1`) should work around the issue.

**Comment by tiparega** [comment]
I needed to add `--global`, as I was using it for installing cdktf. I bet you don't need it if not using it for parent. This worked for me:
```
npm i --global -D functions-have-names
npm install --global cdktf-cli@latest
cdktf get --language java #It works!
```

**Comment by kenkku** [comment]
> How can this break today? Version `0.18.0` is 1 month old.

When you install a package globally, you're only controlling the version of `cdktf-cli`. Transitive dependencies can change, and they can only be controlled by having a lockfile. I don't think there's a way to install something globally and use a lockfile. The actual problem is in a dependency of a dependency of a dependency of a dependency of a dependency of `cdktf-cli`.

**Comment by dingobar** [comment]
Should [the documentation](https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install#install-cdktf) be changed to recommend installing locally with `npm` and invoking through `npx` instead of global installs or homebrew?

**Comment by benkeil** [comment]
Maybe also a good approach for the GitHub action.

**Comment by dingobar** [comment]
> Maybe also a good approach for the GitHub action.

Looks like someone already submitted a PR for that https://github.com/hashicorp/terraform-cdk-action/pull/88

**Comment by DanielMSchmidt** [comment]
We have pinned all dependencies in cdktf 0.20.0, which does not mean that this can not happen again, but it at least limits the risk a bit.
