### ISSUE TITLE
lifecycle: replaceTriggeredBy faulty

### ISSUE THREAD

**Issue by tpaul1611** [hashicorp/terraform-cdk#3196]
### Expected Behavior

When adding lifecycle.replaceTriggeredBy with an ITerraformDependable cdktf should generate valid terraform.

### Actual Behavior

After adding lifecycle.replaceTriggeredBy with an ITerraformDependable cdktf generates invalid terraform.

    "lifecycle": {
      "replace_triggered_by": [
        "${azurerm_subnet.network_default_subnet_6830CB96}"
      ]
    },

The terraform seems to be invalid because string interpolation seems not to be intended for that parameter.

### Steps to Reproduce

Add lifecycle.replaceTriggeredBy with an ITerraformDependable to a resource in typescript.

    lifecycle: {
      replaceTriggeredBy: [iTerraformDependable]
    }

### Versions

language: typescript
cdktf-cli: 0.19.0
node: v18.13.0
cdktf: 0.19.0
constructs: 10.3.0
jsii: null
terraform: 1.5.2
arch: x64
os: win32 10.0.22000

### Providers

┌───────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ azurerm       │ 3.76.0           │       │ ~> 3.70    │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ random        │ 3.5.1            │       │ ~> 3.5     │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ elastic/ec    │ 0.9.0            │       │ ~> 0.9     │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ Azure/azapi   │ 1.9.0            │       │ ~> 1.9     │              │                 │
└───────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Workarounds

I tried the [escape hatch](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch) but ultimately had the same issue.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anuraaga** [comment]
I also ran into this following the docs in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_release

With the `fqn` as in this issue post, it is invalid interpolation, without it, it seems to be infinite recursion.

```
[2023-11-15T17:50:29.384] [ERROR] default - RangeError: Maximum call stack size exceeded
    at keysToSnakeCase (/Users/anuraag/git/jarvis-infra/node_modules/cdktf/lib/util.ts:82:32)
    at /Users/anuraag/git/jarvis-infra/node_modules/cdktf/lib/util.ts:100:15
    at Array.reduce (<anonymous>)
    at keysToSnakeCase (/Users/anuraag/git/jarvis-infra/node_modules/cdktf/lib/util.ts:92:15)
    at /Users/anuraag/git/jarvis-infra/node_modules/cdktf/lib/util.ts:100:15
    at Array.reduce (<anonymous>)
    at keysToSnakeCase (/Users/anuraag/git/jarvis-infra/node_modules/cdktf/lib/util.ts:92:15)
    at /Users/anuraag/git/jarvis-infra/node_modules/cdktf/lib/util.ts:100:15
    at Array.reduce (<anonymous>)
```

**Comment by mike-seagull** [comment]
Here's a workaround that I found to manually build the fqn: https://github.com/hashicorp/terraform-cdk/issues/1866#issuecomment-1155160808
