### ISSUE TITLE
CDKTF: Tailscale provider isn't registered

### ISSUE THREAD

**Issue by TreehouseFalcon** [hashicorp/terraform-cdk#3524]
### Expected Behavior

The Tailscale Terraform provider should allow me to manage my Tailscale resources from Terraform CDK.

### Actual Behavior

The resources and provider for Tailscale I have defined in my infrastructure code are completely ignored. AWS works just fine.

### Steps to Reproduce

1. Add `"tailscale/tailscale@~> 0.14"` to your cdktf.json `terraformProviders` array
2. Add a TailscaleProvider block to the entrypoint in your code
3. Add a TailscaleDeviceKey resource afterwards
4. `cdktf plan` completely ignores installing the provider, doesn't recognize any of the Tailscale resources/provider, completely ignores changes to AWS resources changed at the same time??

### Versions

cdktf 0.17.3
tailscale/tailscale 0.14.0

### Providers

$ cdktf provider list
Error
    at Object.External (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:94:41818)
    at zl.read (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:117:2509)
    at Object.ORt (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:483:34414)
    at kp.handleCommand (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cdktf.js:54:895)
    at N.handler (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cdktf.js:53:30464)
    at C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:8993
    at j (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:4956)
    at _.handleValidationAndGetResult (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:8962)  
    at _.applyMiddlewareAndGetResult (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:9604)   
    at _.runCommand (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:7231)
Collecting Debug Information...
C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error
    at Object.External (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:94:41818)
    at zl.read (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:117:2509)
    at Object.ORt (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:483:34414)
    at kp.handleCommand (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cdktf.js:54:895)
    at N.handler (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\bundle\bin\cdktf.js:53:30464)
    at C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:8993
    at j (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:4956)
    at _.handleValidationAndGetResult (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:8962)  
    at _.applyMiddlewareAndGetResult (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:9604)   
    at _.runCommand (C:\Users\...\AppData\Roaming\nvm\v18.16.0\node_modules\cdktf-cli\node_modules\yargs\build\index.cjs:1:7231) {
  __type: 'External'
}

Node.js v18.16.0

### Workarounds

None

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by TreehouseFalcon** [comment]
Updated issue with attempt on 0.20.4.

**Comment by DanielMSchmidt** [comment]
The debug output indicates that the provider has been added to your `cdktf.json` and I would assume you have the bindings if you were able to add the provider and a resource to your config. Could you share the relevant parts of your code?

**Comment by TreehouseFalcon** [comment]
@DanielMSchmidt Here is a gist showing the file setting up the AWS and Tailscale providers. The TailscaleDeviceKey resource never gets noticed by Terraform and until I delete tailscale from the .gen and purge the dist folder, no other resource changes are noticed as well. It's very odd behavior and only happens with the autogenerated Tailscale provider present.

https://gist.github.com/TreehouseFalcon/ba7362a125dbb3a24ded44f57b6e314f
