### ISSUE TITLE
CDKTF convert: Internal Error: unexpected array

### ISSUE THREAD

**Issue by scraly** [hashicorp/terraform-cdk#3526]
### Expected Behavior

```
$ echo 'resource "ovh_cloud_project_kube" "my_kube_cluster" {
  name         = "my_kube_cluster_cdktf"
  region       = "GRA7"
}' | cdktf convert --language go --provider 'ovh/ovh'
```

--> providing the Go file with the code generated according to the OVH provider (https://registry.terraform.io/providers/ovh/ovh/latest)

### Actual Behavior

Executing the covert command cause an error: `Internal Error: unexpected array`

```
$ echo 'resource "ovh_cloud_project_kube" "my_kube_cluster" {
  name         = "my_kube_cluster_cdktf"
  region       = "GRA7"
}' | cdktf convert --language go --provider 'ovh/ovh'
Internal Error: unexpected array
Error: unexpected array
    at Parser.renderAttributeType (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:205:23)
    at Parser.renderAttributesForBlock (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:264:31)
    at Parser.resourceFrom (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:124:31)
    at ResourceParser.parse (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:458:33)
    at /home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:121
    at Array.map (<anonymous>)
    at TerraformProviderGenerator.buildResourceModels (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:75)
    at /home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:93:31
    at Array.reduce (<anonymous>)
    at convertToTypescript (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:91:79)
Collecting Debug Information...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: unexpected array
    at Parser.renderAttributeType (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:205:23)
    at Parser.renderAttributesForBlock (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:264:31)
    at Parser.resourceFrom (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:124:31)
    at ResourceParser.parse (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/resource-parser.js:458:33)
    at /home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:121
    at Array.map (<anonymous>)
    at TerraformProviderGenerator.buildResourceModels (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/get/generator/provider-generator.js:94:75)
    at /home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:93:31
    at Array.reduce (<anonymous>)
    at convertToTypescript (/home/linuxbrew/.linuxbrew/Cellar/cdktf/0.20.3/libexec/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2cdk/lib/index.js:91:79)
(node:77841) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(Use `node --trace-warnings ...` to show where the warning was created)
Debug Information:
language: typescript
cdktf-cli: 0.20.3
node: v20.11.1
cdktf: 0.20.4
constructs: 10.3.0
jsii: null
terraform: 1.5.7
arch: x64
os: linux 6.1.75-060175-generic
```

### Steps to Reproduce

1. execute 
`$ echo 'resource "ovh_cloud_project_kube" "my_kube_cluster" {
  name         = "my_kube_cluster_cdktf"
  region       = "GRA7"
}' | cdktf convert --language go --provider 'ovh/ovh'`

2. Show the error message

### Versions

language: typescript
cdktf-cli: 0.20.3
node: v20.11.1
cdktf: 0.20.4
constructs: 10.3.0
jsii: null
terraform: 1.5.7
arch: x64
os: linux 6.1.75-060175-generic

### Providers

┌───────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ ovh/ovh       │ 0.37.0           │       │ ~>0.37.0   │              │                 │
└───────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rick-wojciechowski-imprivata** [comment]
Any word on this?  [3111](https://github.com/hashicorp/terraform-cdk/issues/3111) has been closed.  [3170](https://github.com/hashicorp/terraform-cdk/issues/3170) waiting on answer status was removed by bot which seems like an inappropriate action setting.  I am seeing this same issue on conversion to python.  If anyone knows a combination of cdktf and node versions that work, please advise.

**Comment by mutahhir** [comment]
I am unsure why this is happening yet.

The core reason for the (unhelpful, I must add) error is that the provider schema that we're trying to convert seems to be wrong. For each list or set attribute type, it should be an array with two elements, the first one informing us whether it's a set or a list, and the second is the value type. In the above case, we're getting four elements, which are basically two elements duplicated again. 

I tried to chase down where this is coming from, but it isn't clear yet. I'll continue to investigate this.
