### ISSUE TITLE
Allow to specify terraform binary via environment variable

### ISSUE THREAD

**Issue by dethmix** [hashicorp/terraform-cdk#358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is very useful to be able to set path to terraform binary if you use multiple terraform versions. 

You have already implemented this in https://github.com/hashicorp/terraform-cdk/blob/a2387f810d9ca7e4cdcfadbbecab6b43a192f6ee/packages/cdktf-cli/bin/cmds/ui/models/terraform.ts#L4

but still use hardcoded `terraform` as path to binary at 
https://github.com/hashicorp/terraform-cdk/blob/a2387f810d9ca7e4cdcfadbbecab6b43a192f6ee/packages/cdktf-cli/lib/get/generator/provider-schema.ts#L80
#

So as a result we start with `terraform_13` and finish with default `terraform`
```
CDKTF_LOG_LEVEL=debug TERRAFORM_BINARY_NAME="/usr/local/bin/terraform_13" cdktf get
[2020-09-03T23:28:37.761] [DEBUG] default - Terraform v0.13.2

⠙ downloading and generating providers...
[2020-09-03T23:28:37.973] [DEBUG] default -

[2020-09-03T23:28:37.974] [DEBUG] default - Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
⠇ downloading and generating providers...
[2020-09-03T23:28:38.520] [DEBUG] default - - Downloading plugin for provider "aws" (2.70.0)...
⠼ downloading and generating providers...
[2020-09-03T23:28:39.008] [DEBUG] default -

[2020-09-03T23:28:39.008] [DEBUG] default - The following providers do not have any version constraints in configuration,
so the latest version was installed.

[2020-09-03T23:28:39.008] [DEBUG] default -

[2020-09-03T23:28:39.008] [DEBUG] default - To prevent automatic upgrades to new major versions that may contain breaking

[2020-09-03T23:28:39.008] [DEBUG] default - changes, it is recommended to add version = "..." constraints to the

[2020-09-03T23:28:39.008] [DEBUG] default - corresponding provider blocks in configuration, with the constraint strings

[2020-09-03T23:28:39.009] [DEBUG] default - suggested below.

[2020-09-03T23:28:39.010] [DEBUG] default -
* provider.aws: version = "~> 2.70"


[2020-09-03T23:28:39.010] [DEBUG] default - Terraform has been successfully initialized!


[2020-09-03T23:28:39.010] [DEBUG] default - You may now begin working with Terraform. Try running "terraform plan" to see

[2020-09-03T23:28:39.010] [DEBUG] default - any changes that are required for your infrastructure. All Terraform commands
should now work.


[2020-09-03T23:28:39.010] [DEBUG] default - If you ever set or change modules or backend configuration for Terraform,

[2020-09-03T23:28:39.010] [DEBUG] default - rerun this command to reinitialize your working directory. If you forget, other

[2020-09-03T23:28:39.010] [DEBUG] default - commands will detect it and remind you to do so if necessary.

[2020-09-03T23:28:39.037] [DEBUG] default - Too many command line arguments. Configuration path expected.

Too many command line arguments. Configuration path expected.
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/usr/local/Cellar/cdktf/0.0.17/libexec/lib/node_modules/cdktf-cli/lib/util.js:99:27)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
non-zero exit code 1

 ~/terraform_sandbox/cdktf$ terraform -version
Terraform v0.11.14
```

**Comment by cmclaughlin** [comment]
Not (yet?) an official recommendation for this project, but I use tfenv.

This might solve it for you...

```
brew install tfenv
tfenv insall 0.13.2
tfenv use 0.13.2
```
You can also pin the terraform version in your cdk stacks like this.

```
echo 0.13.2 > .terraform-version
```

**Comment by jsteinich** [comment]
@dethmix I would actually consider this a bug. If you are interested, a PR would be appreciated.

**Comment by dpavlov-smartling** [comment]
Hello @jsteinich I am not a js/ts programmer, but following changes solved mentioned issue 
```
git diff
diff --git a/packages/cdktf-cli/lib/get/generator/provider-schema.ts b/packages/cdktf-cli/lib/get/generator/provider-schema.ts
index 62b43e8..71f4168 100644
--- a/packages/cdktf-cli/lib/get/generator/provider-schema.ts
+++ b/packages/cdktf-cli/lib/get/generator/provider-schema.ts
@@ -4,6 +4,7 @@ import { promisify } from 'util';
 import { exec, withTempDir } from '../../util';

 const writeFile = promisify(fs.writeFile);
+const terraformBinaryName = process.env.TERRAFORM_BINARY_NAME || 'terraform'

 export interface ProviderSchema {
   format_version: '1.0';
@@ -76,8 +77,8 @@ export async function readSchema(providers: string[]): Promise<ProviderSchema> {

     // todo: when implementing logging, we need to make sure we can show the terraform init
     // output if the log level is set to debug
-    await exec('terraform', [ 'init' ], { cwd: outdir });
-    schema = await exec('terraform', ['providers', 'schema', '-json'], { cwd: outdir });
+    await exec(terraformBinaryName, [ 'init' ], { cwd: outdir });
+    schema = await exec(terraformBinaryName, ['providers', 'schema', '-json'], { cwd: outdir });
     fs.unlinkSync(filePath)
   })

```

I can try to create a PR if I could push my branch or you can add it. 

@cmclaughlin thanks for the note about **tfenv**!
Thanks

**Comment by dethmix** [comment]
@jsteinich I am not a ts/js developers, but following changes solved mentioned issue 
```
diff --git a/packages/cdktf-cli/lib/get/generator/provider-schema.ts b/packages/cdktf-cli/lib/get/generator/provider-schema.ts
index 62b43e8..71f4168 100644
--- a/packages/cdktf-cli/lib/get/generator/provider-schema.ts
+++ b/packages/cdktf-cli/lib/get/generator/provider-schema.ts
@@ -4,6 +4,7 @@ import { promisify } from 'util';
 import { exec, withTempDir } from '../../util';

 const writeFile = promisify(fs.writeFile);
+const terraformBinaryName = process.env.TERRAFORM_BINARY_NAME || 'terraform'

 export interface ProviderSchema {
   format_version: '1.0';
@@ -76,8 +77,8 @@ export async function readSchema(providers: string[]): Promise<ProviderSchema> {

     // todo: when implementing logging, we need to make sure we can show the terraform init
     // output if the log level is set to debug
-    await exec('terraform', [ 'init' ], { cwd: outdir });
-    schema = await exec('terraform', ['providers', 'schema', '-json'], { cwd: outdir });
+    await exec(terraformBinaryName, [ 'init' ], { cwd: outdir });
+    schema = await exec(terraformBinaryName, ['providers', 'schema', '-json'], { cwd: outdir });
     fs.unlinkSync(filePath)
   })
```

I can try to create a PR if I could push my branch, or you can do this from your side. 

@cmclaughlin thank you for the note about **tfenv**

**Comment by jsteinich** [comment]
Thanks @dethmix. If you push your change to a branch in your fork, it's pretty easy to create a PR, but I'm happy to take over if you'd rather.

**Comment by skorfmann** [comment]
@dethmix thanks for raising this issue!

@cmclaughlin 
> Not (yet?) an official recommendation for this project, but I use tfenv.

Yes, `tfenv` works quite well for me as well. Similar tools, e.g. `asdf`, should work as well.

@jsteinich 
>  I would actually consider this a bug. If you are interested, a PR would be appreciated.

Agreed, that's a bug.

**Comment by dpavlov-smartling** [comment]
@jsteinich I will try to create PR, thx

**Comment by dethmix** [comment]
@jsteinich I will try to create PR, thx

**Comment by skorfmann** [comment]
Resolved by https://github.com/hashicorp/terraform-cdk/pull/366
