### ISSUE TITLE
CLI: HCL synth fails on ignore changes

### ISSUE THREAD

**Issue by Hi-Fi** [hashicorp/terraform-cdk#3697]
### Expected Behavior

Stack is synthesized corretly as HCL

### Actual Behavior

Crash with error:
```
npm run cdktf synth -- --hcl

> test-repo@1.0.0 cdktf
> cdktf synth --hcl


⠹  Synthesizing
[2024-08-09T10:57:17.900] [ERROR] default - /Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:505
    ...Object.entries(jsonObject).map(([name, value]) => {
              ^

[2024-08-09T10:57:17.901] [ERROR] default - TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at renderFuzzyJsonObject (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:505:15)
    at renderFuzzyJsonExpression (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:525:12)
    at /Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:670:29
    at Array.map (<anonymous>)
    at renderAttributes (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:586:6)
    at renderModule (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:372:3)
    at /Users/user/test-repo/node_modules/cdktf/lib/terraform-stack.ts:292:49
    at Array.map (<anonymous>)
ERROR: cdktf encountered an error while synthesizing

Synth command: npx ts-node bin/main.ts
Error:         non-zero exit code 1

Command output on stderr:

    /Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:505
        ...Object.entries(jsonObject).map(([name, value]) => {
                  ^
    TypeError: Cannot convert undefined or null to object
        at Function.entries (<anonymous>)
        at renderFuzzyJsonObject (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:505:15)
        at renderFuzzyJsonExpression (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:525:12)
        at /Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:670:29
        at Array.map (<anonymous>)
        at renderAttributes (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:586:6)
        at renderModule (/Users/user/test-repo/node_modules/cdktf/lib/hcl/render.ts:372:3)
        at /Users/user/test-repo/node_modules/cdktf/lib/terraform-stack.ts:292:49
        at Array.map (<anonymous>)
        at RunnerAcrStack.toHclTerraform (/Users/user/test-repo/node_modules/cdktf/lib/terraform-stack.ts:268:8)




⠧  Synthesizing
```

### Steps to Reproduce

1. Create stack with resource that has ignore_changes set to single item
2. Try to synthesize stack to HCL (cdktf synth --hcl)

### Versions

language: typescript
cdktf-cli: 0.20.8
node: v20.13.1
cdktf: 0.20.8
constructs: 10.3.0
jsii: null
terraform: 1.9.4
arch: arm64
os: darwin 23.6.0

### Providers

None

### Possible Solutions

Check handling of data in HCL render function.

With some console logging in `renderFuzzyJsonExpression` (like:
```javascript
function renderFuzzyJsonExpression(jsonExpression) {
    console.log(jsonExpression);
    console.log(typeof jsonExpression)
```

output was:
```
    { ignore_changes: [ 'tags' ] }
    [ 'tags' ]
    object
    tags
    string
    null
    object
```

### Workarounds

Don't synth HCL

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Hi-Fi** [comment]
Apparently (unit tests) issue is not at the ignore_changes block, so have to check things a bit more.

**Comment by mutahhir** [comment]
This needs a bit more clarity. I guess the issue is that in certain conditions, passing a null value to attribute causes the error. Can you give me a minimal reproducible code snippet to chase this down?
