### ISSUE TITLE
CDK works for Typescript but not Python on Windows 10 Version 10.0.19041 Build 19041

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [hashicorp/terraform-cdk#410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDK version = 0.0.17-pre.06e13a2348f6cefd0b65c65fc99c081e108e6878
Python version = 3.8.3

### Affected Resource(s)

CDK projects for Python on Windows 10 Version 10.0.19041 Build 19041

### Debug Output

I get the following output when running `cdktf init --template=python`

```
Error: Unprocessable Entity
    at ClientRequest.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\cdktf-cli\bin\cmds\helper\terraform-cloud-client.js:3
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
```

### Expected Behavior

A CDK project should be initialized

### Steps to Reproduce

Run the following: `cdktf init --template=python`

**Comment by jsteinich** [comment]
I believe @next (pre) versions aren't yet supported for python (see https://github.com/hashicorp/terraform-cdk/issues/293). Try rolling back to 0.0.17.

**Comment by DanielMSchmidt** [comment]
I think this is solved , our windows tests don't have any problems with python it seems. If this is still an issue please let me know and I'll reopen the issue 👍
