### ISSUE TITLE
JSII compilation failed {cloudwatch,iam,route53} error TS6133: 'options' is declared but its value is never read.

### ISSUE THREAD

**Issue by rrrix** [hashicorp/terraform-cdk#563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

MacOS Catalina 10.15.7
Python.org distribution of Python3.9.1 

```
$ cdktf --version
0.1.0

$ python3 --version
Python 3.9.1

$ pip3 freeze
attrs==20.3.0
cattrs==1.1.2
cdktf==0.1.0
constructs==3.3.20
jsii==1.20.1
publication==0.0.3
python-dateutil==2.8.1
six==1.15.0
typing-extensions==3.7.4.3

$ cat requirements.txt
cdktf~=0.1.0.dev188
```

### Debug Output

Full gist: https://gist.github.com/rrrix/fbf5d9df9675b7307b19b1b6dd468fab

Important bit: 
```
~/git/work/cdktf/confluence $ cdktf get
⠴ downloading and generating modules...
NOTE: Temp directory retained due to an error: /var/folders/q9/zqdm6xf16g537l69fy68y9zm0000gn/T/temp-Ydk3RY
Error: jsii compilation failed with non-zero exit code: 1
  | [2021-02-12T17:20:24.732] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | modules/terraform-aws-modules/cloudwatch/aws.ts:9:52 - error TS6133: 'options' is declared but its value is never read.
  | 9   public constructor(scope: Construct, id: string, options: CloudwatchOptions = {}) {
  |                                                      ~~~~~~~
  | modules/terraform-aws-modules/iam/aws.ts:9:52 - error TS6133: 'options' is declared but its value is never read.
  | 9   public constructor(scope: Construct, id: string, options: IamOptions = {}) {
  |                                                      ~~~~~~~
  | modules/terraform-aws-modules/route53/aws.ts:9:52 - error TS6133: 'options' is declared but its value is never read.
  | 9   public constructor(scope: Construct, id: string, options: Route53Options = {}) {
  |                                                      ~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /Users/me/.config/yarn/global/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/q9/zqdm6xf16g537l69fy68y9zm0000gn/T/temp-Ydk3RY
  +----------------------------------------------------------------------------------
    at newError (/Users/me/.config/yarn/global/node_modules/jsii-srcmak/lib/util.js:38:20)
    at ChildProcess.<anonymous> (/Users/me/.config/yarn/global/node_modules/jsii-srcmak/lib/util.js:55:29)
    at Object.onceWrapper (node:events:483:26)
    at ChildProcess.emit (node:events:376:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
```

### Expected Behavior

`cdktf get` exits successfully.

### Actual Behavior

`cdktf get` throws an error.

### Steps to Reproduce

This is a brand new cdktf project, just created with `cdktf init --template python-pip`. 

cdktf.json: https://gist.github.com/rrrix/fbf5d9df9675b7307b19b1b6dd468fab#file-cdktf-json 

### Important Factoids

This is my very first project / attempt at using `cdktf` and Terraform. I'm a veteran of the "classic" CDK (with TypeScript) however. I want to come to the dark side! :vader:

**Comment by rrrix** [comment]
Git repo to reproduce: https://github.com/rrrix/cdktf-issue-563 

Again, using version `cdktf~=0.1.0` which AFAIK is the latest version.

```
$ cdktf --version
0.1.0
```

Also removed everything but `cloudwatch`, `iam`, and `route53` from the `terraformModules` array.

**Comment by skorfmann** [comment]
That's unfortunately not working right now - see #520 - The good news is, that better module support (see #522) is pretty much the next feature we're going to tackle. You could still use the [TerraformModule](https://github.com/hashicorp/terraform-cdk/blob/00af7818808bf6ecd28a8ad0b051586b6a688042/packages/cdktf/lib/terraform-module.ts) class in the meantime. That's pretty much the equivalent to using modules in plain HCL.

**Comment by michaelmisshore** [comment]
> That's unfortunately not working right now - see #520 - The good news is, that better module support (see #522) is pretty much the next feature we're going to tackle. You could still use the [TerraformModule](https://github.com/hashicorp/terraform-cdk/blob/00af7818808bf6ecd28a8ad0b051586b6a688042/packages/cdktf/lib/terraform-module.ts) class in the meantime. That's pretty much the equivalent to using modules in plain HCL.

Do you have any references to working examples of using the [TerraformModule](https://github.com/hashicorp/terraform-cdk/blob/00af7818808bf6ecd28a8ad0b051586b6a688042/packages/cdktf/lib/terraform-module.ts) class to, let's say, include the IAM module for now?

**Comment by skorfmann** [comment]
> > That's unfortunately not working right now - see #520 - The good news is, that better module support (see #522) is pretty much the next feature we're going to tackle. You could still use the [TerraformModule](https://github.com/hashicorp/terraform-cdk/blob/00af7818808bf6ecd28a8ad0b051586b6a688042/packages/cdktf/lib/terraform-module.ts) class in the meantime. That's pretty much the equivalent to using modules in plain HCL.
> 
> Do you have any references to working examples of using the [TerraformModule](https://github.com/hashicorp/terraform-cdk/blob/00af7818808bf6ecd28a8ad0b051586b6a688042/packages/cdktf/lib/terraform-module.ts) class to, let's say, include the IAM module for now?

Yes, with the recently released version `0.2.0` you can do it [like this](https://github.com/hashicorp/terraform-cdk/blob/ac228f95617085b36982d3516ab1f15428c836d6/test/typescript/modules/main.ts)

**Comment by jsteinich** [comment]
@rrrix since version `0.2.0` submodules are now supported if you explicitly specify which ones you'd like to use like this: `"terraform-aws-modules/iam/aws//modules/iam-account@~> 3.0"`. Does that meet your needs?

**Comment by rrrix** [comment]
@jsteinich yeah that will be fine I think - is that documented anywhere other than here? I'll forget when I need it :)

**Comment by jsteinich** [comment]
> @jsteinich yeah that will be fine I think - is that documented anywhere other than here? I'll forget when I need it :)

It really isn't. Made an issue to track updating the documentation: #718.

**Comment by DanielMSchmidt** [comment]
Looks to me like the issue is solved and #718 got merged so I will close this 👍
