### ISSUE TITLE
cdktf get fails with "TypeError: Cannot read property 'match' of undefined" using google module

### ISSUE THREAD

**Issue by alexjmoore** [hashicorp/terraform-cdk#613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Node 14.6.0
Python 3.7.3
Terraform 0.14.9
cdktf 0.2.0 and 0.2.1 (NOTE: issue is **not** present in 0.1.0)

### Affected Resource(s)

Module: terraform-google-modules/network/google

### Debug Output

Full debug output here: https://gist.githubusercontent.com/alexjmoore/e0554867c194af530ae9f92ccd15bcc4/raw/48e309902ff60aa784d7e9ff8a4cf3a76b545693/gistfile1.txt

### Expected Behavior

I would expect cdktf to pull in the modules without issue.

### Actual Behavior

`cdktf get` results in:

```
[2K[1A[2K[G⠸ downloading and generating modules and providers...
[2K[1A[2K[GTypeError: Cannot read property 'match' of undefined
    at transformVariables (/usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:43:46)
    at harvestModuleSchema (/usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:89:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:133:28
    at async Object.withTempDir (/usr/lib/node_modules/cdktf-cli/lib/util.js:41:9)
    at async Object.readSchema (/usr/lib/node_modules/cdktf-cli/lib/get/generator/provider-schema.js:124:5)
    at async ConstructsMaker.generateTypeScript (/usr/lib/node_modules/cdktf-cli/lib/get/constructs-maker.js:160:24)
    at async ConstructsMaker.generate (/usr/lib/node_modules/cdktf-cli/lib/get/constructs-maker.js:174:9)
    at async get (/usr/lib/node_modules/cdktf-cli/bin/cmds/ui/get.js:50:17)
⠸ downloading and generating modules and providers...
Cannot read property 'match' of undefined
```

### Steps to Reproduce

Use the following `cdktf.json`:

```
{
  "language": "python",
  "app": "python3 ./main.py",
  "terraformProviders": ["google@~>3.0"],
  "terraformModules": ["terraform-google-modules/network/google@3.0.0"],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
"allowSepCharsInLogicalIds": "true"
  }
}
```

### References

* #0000

**Comment by jsteinich** [comment]
Likely the same issue as #596.
