### ISSUE TITLE
Providers generated on Windows don't work on Linux

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#794]
> > The contents were different between `cdktf get` runs on Windows and Linux machines.
> 
> Are there more differences than just line endings? Likely something that could be improved if so.

As a matter of fact, there is:

```
[Container] 2021/06/23 09:58:56 Running command cdktf synth
cdktf encountered an error while synthesizing

Synth command: pipenv run python main.py
Error:         non-zero exit code 1

Command output on stderr:

    jsii.errors.JavaScriptError: 
      internal/modules/cjs/loader.js:303
            throw err;
            ^
  
      Error: Cannot find module '/tmp/jsii-kernel-7PD2Kw/node_modules/hashicorp_aws/providers\aws\index.js'. Please verify that the package.json has a valid "main" entry
          at tryPackage (internal/modules/cjs/loader.js:295:19)
          at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
          at Module._load (internal/modules/cjs/loader.js:667:27)
          at nodeRequire (/tmp/tmplj38tl2q/lib/program.js:7809:42)
          at /tmp/jsii-kernel-7PD2Kw/node_modules/hashicorp_aws:1:1
          at Script.runInContext (vm.js:130:18)
          at Kernel._execute (/tmp/tmplj38tl2q/lib/program.js:8588:31)
          at Kernel.load (/tmp/tmplj38tl2q/lib/program.js:7856:38)
          at KernelHost.processRequest (/tmp/tmplj38tl2q/lib/program.js:9479:36)
```

The `imports` were created on a Windows machine, and the `synth` command was executed on AWS CodeBuild in a Ubuntu build container. Looks like the generated code contains some Windows path separators that don't work on Linux...

_Originally posted by @onitake in https://github.com/hashicorp/terraform-cdk/issues/791#issuecomment-866843698_

**Comment by surajgawas110** [comment]
Even i m facing same issue. :(
CDKTF Java - working on windows, failing to synth via docker nodejs container.

![image](https://user-images.githubusercontent.com/48012652/157421384-0a1b006e-3de8-41d0-a87f-dae29eb2db35.png)

**Comment by surajgawas110** [comment]
Found one workaround while doing R&D, **if we create cdktf new project in linux env and then move it to windows it works on both os.** But if you create project on windows you will face this issue.  

So if you are facing above issue just create new project copy all changes that you made to the template and then try cdktf synth on linux just to confirm its working on linux, then you can compress tha code and move it windows.
