### ISSUE TITLE
Error on Github Actions on deploy step

### ISSUE THREAD

**Issue by chengjiaapraamcos** [hashicorp/terraform-cdk#827]
I got error when building on Github Actions pipeline with my own runner container.

Error: 

```
> cdktf get

Generated typescript constructs in the output directory: .gen
Generated Terraform code for the stacks: xxx
Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
    at App.handleSetRawMode (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/ink/build/components/App.js:56:27)
    at /home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/ink/build/hooks/use-input.js:38:9
    at Ue (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:108:200)
    at mg (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:156:231)
    at exports.unstable_runWithPriority (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/scheduler/cjs/scheduler.production.min.js:18:437)
    at hc (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:29:325)
    at Vf (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:155:214)
    at /home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:155:121
    at X (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/scheduler/cjs/scheduler.production.min.js:17:184)
    at Timeout.t [as _onTimeout] (/home/ec2-user/actions-runner/_work/github-runner-terraform-cdk-test/github-runner-terraform-cdk-test/node_modules/scheduler/cjs/scheduler.production.min.js:11:145)
Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.

Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported

 - Read about how to prevent this error on
   https://github.com/vadimdemedes/ink/#israwmodesupported
 - App.handleSetRawMode (node_modules/ink/build/components/App.js:56:27)
 -  (node_modules/ink/build/hooks/use-input.js:38:9)
 -Ue (node_modules/react-reconciler/cjs/react-reconciler.production.min.js:108:
    200)
 -mg (node_modules/react-reconciler/cjs/react-reconciler.production.min.js:156:
    231)
 -exports.unstable_runWithPr (node_modules/scheduler/cjs/scheduler.production.m
  ority                     in.js:18:437)
 -hc (node_modules/react-reconciler/cjs/react-reconciler.production.min.js:29:3
    25)
 -Vf (node_modules/react-reconciler/cjs/react-reconciler.production.min.js:155:
    214)
 - (node_modules/react-reconciler/cjs/react-reconciler.production.min.js:155:12
  1)
 - X (node_modules/scheduler/cjs/scheduler.production.min.js:17:184)
 - Timeout.t (node_modules/scheduler/cjs/scheduler.production.min.js:11:145)

Error: Process completed with exit code 1.

```

Anyone can help? Thanks

**Comment by vsapronov** [comment]
@chengjiaapraamcos have you figured out how to fix this issue?
I have got the same on AWS codebuild job, seems something to do with TTY setup.

**Comment by jamiegs** [comment]
> @chengjiaapraamcos have you figured out how to fix this issue? I have got the same on AWS codebuild job, seems something to do with TTY setup.

If you're doing a `cdktf deploy` you might need to use  `cdktf deploy $stackname --auto-approve`

**Comment by jsteinich** [comment]
Could also try setting the `CI` environment variable to `1` or `true`

**Comment by surajgawas110** [comment]
cdktf deploy _StackName_ --auto-approve           ===> this worked for me 
![image](https://user-images.githubusercontent.com/48012652/155397837-b298cea3-558b-4040-8432-4656bbd8449f.png)
