### ISSUE TITLE
Getting error at the time of cdktf get

### ISSUE THREAD

**Issue by lekhrajsinghrajput** [hashicorp/terraform-cdk#908]
I'm using python for my cdktf project and when I am trying to do cdktf get I'm getting the following error.
```
Error: jsii compilation failed with non-zero exit code: null
  | 
  +----------------------------------------------------------------------------------
  | Command: /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-HyijUR
  +----------------------------------------------------------------------------------
    at newError (/usr/lib/node_modules/cdktf-cli/node_modules/jsii-srcmak/lib/util.js:38:20)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cdktf-cli/node_modules/jsii-srcmak/lib/util.js:55:29)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
⠏ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: null
  | 
  +----------------------------------------------------------------------------------
  | Command: /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /tmp/temp-HyijUR
  +----------------------------------------------------------------------------------
```

When I tried the command specified in the error, I'm getting the following result.

```
Error: Error: Cannot find module '/root/testing/package.json'
Require stack:
- /usr/lib/node_modules/cdktf-cli/node_modules/jsii/lib/project-info.js
- /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii.js
- /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.loadProjectInfo (/usr/lib/node_modules/cdktf-cli/node_modules/jsii/lib/project-info.js:19:17)
    at /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii.js:67:46
    at Object.<anonymous> (/usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

---------------------------------------------------------------------------------------------------
Please help me to resolve this problem.

content of the cdktf.json file
```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "terraformProviders": ["aws@~> 3.42"],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
"allowSepCharsInLogicalIds": "true"
  }
}
```

**Comment by ansgarm** [comment]
Hi @lekhrajsinghrajput,

thank you for posting your `cdktf.json` config file.
Which CDK for Terraform version are you using?

Your error also looks similar to the bug reported in #879

**Comment by lekhrajsinghrajput** [comment]
Hi @ansgarm,
I'm using terraform 1.0.0 version and using the following docker file.
```
FROM ubuntu

ARG TERRAFORM_VERSION=1.0.0
ARG CDKTF_VERSION=v0.5.0

RUN apt-get update && \
apt-get install vim git curl unzip -y && \
mkdir -p /opt/terraform && \
cd /opt/terraform && \
curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
echo "PATH=$PATH:/opt/terraform" >> ~/.bashrc && \
curl -sL https://deb.nodesource.com/setup_16.x | bash -  && \
apt-get install -y nodejs && \
apt-get install python3.8 -y  && \

ln -s /usr/bin/python3 /usr/bin/python && \
apt-get install python3-pip -y  && \
pip install pipenv && \
npm install cdktf-cli@${CDKTF_VERSION} -g 

```

**Comment by ansgarm** [comment]
Hi @lekhrajsinghrajput,

I just created a Docker Image using the Dockerfile you specified and tried to reproduce the issue you're running into with the `cdktf.json` you posted.
The `cdktf get` took quite a while but worked. The `aws` Terraform provider takes quiet some time and resources to generate.

How much memory does your Docker container get?

**Comment by lekhrajsinghrajput** [comment]
I haven't restrict my containers to use memory.

**Comment by ansgarm** [comment]
Which is your host OS for Docker? E.g. on my Mac the default memory given to Docker containers was 2GB I think 😅

**Comment by lekhrajsinghrajput** [comment]
Yes, It was due to the memory available for my container(2 GB).
